modify strings for use with translation
n-rook/thscoreboard pull request #109
Opened 2022-11-15 03:14 UTC by raviddog

I edited the .po files with poedit, seems to work fine
Since we're using translation, the strings we write in the code don't need to be formatted the way you would for a frontend, and in fact should contain additional context information to make it clear where the string will be found

E.g. I've added the game id to every shot name string, so that you can tell what it is in the translation editor, instead of just seeing 12 lines of "ReimuA"

Also if we intentionally make the base strings look bad, it will be more obviously out of place if we've forgotten a translation

2022-11-15 03:14 UTC, raviddog commented
addresses #66

2022-11-15 03:17 UTC, raviddog commented
Not sure what to do about the test situation

2022-11-15 03:21 UTC, raviddog commented
#58 appears to be related too

2022-11-15 03:29 UTC, raviddog commented
For what its worth, the tests pass on my local machine, so this might be #58 kicking in

2022-11-15 04:34 UTC, n-rook commented
> #58 appears to be related too

Yes, I think this is unfortunately #58. For this PR I would just work around it in one hacky way or another (maybe change the assertions so they're more general and both accept the untranslated string and the translated one), because #58 seems like it will be a pain in the ass to fix and you definitely won't want to do it as part of this.

2022-11-15 04:35 UTC, n-rook requested changes

2022-11-15 04:35 UTC, n-rook commented on project/thscoreboard/replays/game_ids.py
> +from django.utils.translation import gettext as _
I think we should keep using pgettext, rather than putting context in the translation string itself. It is true that putting context in the translation string has the advantage that it makes untranslated strings look really ugly (and thus tells us we should translate them). But I don't see any benefit to translating strings that are already in English. And the downside is that it makes it more difficult to understand exactly what the strings are going to look like on the website; we have to mentally delete the context part first. gettext already has a way to add context for strings; we might as well use it rather than trying to invent our own alternative.

2022-11-15 04:35 UTC, n-rook commented on project/thscoreboard/replays/forms.py
> +    ('4', _('Private'))
Why move to ints from strings for the category names? I don't think the strings were doing any harm. I mean, I don't think there's anything wrong with the ints either, but strings would be easier to read if I were looking at the request in the Chrome debugger or something like that.

2022-11-15 04:35 UTC, n-rook commented on README.md
> +### Adding support for new games
Nice, this is good to have written up

2022-11-15 04:35 UTC, n-rook commented on project/thscoreboard/replays/forms.py
> -game_names = (
Thanks for cleaning up this junk in this file.

2022-11-15 04:38 UTC, raviddog commented on project/thscoreboard/replays/forms.py
> +    ('4', _('Private'))
had to do that to make this fit in to replace pulling the model itself for the dropdown box, so that we could translate those strings

2022-11-15 04:39 UTC, raviddog commented on project/thscoreboard/replays/game_ids.py
> +from django.utils.translation import gettext as _
i was typing a reply that aaid idk what the difference between the two is, and then i realised the difference, so yeah ok ill change this

2022-11-15 14:34 UTC, n-rook commented on project/thscoreboard/replays/forms.py
> +    ('4', _('Private'))
oh OK

2022-11-21 15:15 UTC, n-rook approved these changes
Looks good once updated from master (which I think should be easy, iirc there isn't anything that _really_ conflicts with this PR in there)

2022-11-22 02:05 UTC, raviddog commented
i already did

2022-11-22 02:21 UTC, n-rook commented
oh ok :D

2022-11-22 03:02 UTC, merged