uWGSI, automatic deployment
n-rook/thscoreboard pull request #112
Opened 2022-11-18 17:07 UTC by 32th-System

2022-11-18 23:26 UTC, n-rook requested changes
Nice, this is really great!

2022-11-18 23:26 UTC, n-rook commented on ref/server/silentselene.service
> +KillSignal=SIGINT
Huh, what was wrong with SIGTERM?

2022-11-18 23:26 UTC, n-rook commented on ref/server/nginx/silentselene
> +                root /home/silentselene/silentselene/project/thscoreboard/shared_content;
I think we will be better off if we run "compilescss" and "collectstatic", and then expose staticfiles, rather than exposing shared_content directly. That way you don't have to do stuff like refer into dist-packages. You can see the script I used for heroku deployments in `bin/post_compile`; I think that's pretty much what we would want here too (although maybe not running the commands through the shell like that).

2022-11-18 23:36 UTC, 32th-System commented on ref/server/silentselene.service
> +KillSignal=SIGINT
the docs recommend SIGINT or SIGQUIT and say
> Sending the SIGTERM signal will obtain the same result reload-wise but will not wait for the completion of running requests.

2022-11-19 00:56 UTC, 32th-System commented on project/thscoreboard/thscoreboard/autodeploy.py
> +        if 'Deploy-Key' in request.headers and request.headers['Deploy-Key'] == settings.DEPLOY_KEY:
Since HTTP basic authentication also asks for a username I decided to do authentication with user accounts. Superusers can use /deploy

2022-11-19 13:35 UTC, 32th-System commented on ref/server/nginx/silentselene
> +                root /home/silentselene/silentselene/project/thscoreboard/shared_content;
I implemented that though I have one question: what are your thoughts on writing CSS directly rather than compiling SASS into CSS? From what I've seen with our SASS file and the CSS it compiled to SASS is just CSS with no curly braces or semicolons so I really don't get why we don't just write CSS directly

2022-11-19 15:11 UTC, n-rook approved these changes

2022-11-19 15:11 UTC, n-rook commented on ref/server/silentselene.service
> +KillSignal=SIGINT
Ah, makes sense.

2022-11-19 15:11 UTC, n-rook commented on ref/server/nginx/silentselene
> +                root /home/silentselene/silentselene/project/thscoreboard/shared_content;
The big advantage is nesting--- you can't nest CSS rules inside other rules like you can with SASS (or SCSS). The mixins are also really useful. We aren't really using the mixins much right now but we do use nesting, and I think it makes things much easier to read.

There are actually two very similar types called "SASS" and "SCSS"; SASS is the one we use, and it's where the slightly different syntax comes from. SCSS has all the same features but has regular CSS syntax.

2022-11-19 15:16 UTC, merged