Staff features
n-rook/thscoreboard pull request #134
Opened 2022-12-08 12:16 UTC by 32th-System

This includes the ability for staff to delete other people's replays and a new feature for users to edit the comment on their replays (and for staff to edit the comment on anyone's replays)

2022-12-09 19:46 UTC, n-rook requested changes
Very neat!

First JavaScript 😲

2022-12-09 19:46 UTC, n-rook commented on project/thscoreboard/replays/views/view_replay.py
> +    if request.method == 'POST':
I think this should go to a different URL, rather than the POST happening on the same URL. After all, someday maybe we'll have multiple of these edit options, and it'd be awkward to handle them all in the same place. This can be controlled by https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-action.

2022-12-09 19:46 UTC, n-rook commented on project/thscoreboard/replays/views/view_replay.py
> +        'is_owner': request.user == replay_instance.user or request.user.is_staff,
I think this is a bit confusing; I would expect "is_owner" to be set only if the user is the person who uploaded the replay. I'd rather see us add a new variable, called something like "can_edit" or something.

2022-12-09 19:46 UTC, n-rook commented on project/thscoreboard/replays/views/view_replay.py
> +        if edit_comment.is_valid() and (replay_instance.user == request.user or request.user.is_staff):
So... I don't think we should let mods edit comments, and here's why: The comment is something that, on the website, we're claiming was said by the user. As such, I worry that if we let mods edit comments, we are basically putting words in someone else's mouth. Maybe we will want it at some point, but it's the sort of feature which I think we need to be really careful about how we add. At the very least, we'd need some sort of notice so users know the comment was edited by a mod.

2022-12-09 19:46 UTC, n-rook commented on project/thscoreboard/shared_content/static/js/replays/replay_details.js
> +    let el = document.getElementById("replay-comment-edit");
Rather than setting display = "none" on load, can we just set display = "none" in the CSS?

2022-12-09 20:05 UTC, 32th-System commented on project/thscoreboard/shared_content/static/js/replays/replay_details.js
> +    let el = document.getElementById("replay-comment-edit");
I did this so that if JavaScript is disabled the edit box is still available

2022-12-09 20:09 UTC, n-rook commented on project/thscoreboard/shared_content/static/js/replays/replay_details.js
> +    let el = document.getElementById("replay-comment-edit");
oh that makes sense. can you add a comment here saying that?

2022-12-10 00:20 UTC, n-rook approved these changes
\o/

2022-12-10 00:21 UTC, merged