Th09
n-rook/thscoreboard pull request #135
Opened 2022-12-11 12:27 UTC by raviddog

The replay details is sort of a mess, and doesn't really say much. But the replays themselves don't have that much info anyway. Importantly, final score is not saved, and so we might actually for the first time need to let users enter their own score and have rep_score fields be different from the actual score (and show it on the frontend).

2022-12-11 12:51 UTC, raviddog commented
I would prefer to merge this now, and create an issue for adjusting the frontend + proper score submission, if that's fine with people

2022-12-11 16:49 UTC, n-rook requested changes

2022-12-11 16:49 UTC, n-rook commented on project/thscoreboard/replays/create_replay.py
> +        shot_instance = None
nitpick: IMO this part of the code would be clearer if you first created the ReplayStage instance, and then did `if replay_info.game == game_ids.GameIDs.TH09:` and set stuff on the instance then. like,

```
replay_stage = ...

if replay_info.game == game_ids.GameIDs.TH09:
  shot_instance = ...
  etc

replay_stage.save()
```

2022-12-11 16:49 UTC, n-rook commented on project/thscoreboard/replays/views/create_replay.py
>      replay_info = replay_parsing.Parse(bytes(temp_replay.replay))
I totally get why you want to merge this PR; trying to do additional work on top of this would get really unwieldy really fast. However, I don't think this is quite ready for users yet.

As such, I think probably the right thing to do is actually to use the DEBUG setting and not let people upload th09 replays outside of debug. You can import DEBUG from https://docs.djangoproject.com/en/4.1/topics/settings/#using-settings-in-python-code, and then raise an error if the replay is PoFV. It'd probably be best to do this under upload_file().

Of course... it does not really matter if it is ready for users yet, since we have not released. But I figure it is good to get in the habit, and what I'm suggesting should be a easy change. This way we will know what to do when adding new games later.

2022-12-12 02:57 UTC, raviddog commented on project/thscoreboard/replays/create_replay.py
> +        shot_instance = None
I'm not sure about that, I think when i create the ReplayStage instance, I want to have every single field in there rather than having them spread out. It makes it easier to notice when a field has been missed.

2022-12-12 03:41 UTC, raviddog commented on project/thscoreboard/replays/views/create_replay.py
>      replay_info = replay_parsing.Parse(bytes(temp_replay.replay))
I think the actual replay parsing and uploading is all fine, it's just that the frontend is a little bit ugly, which I'm not sure we care about that much right now. I was just mainly concerned that editing the form would be a lot of work, but I'm managed to do it now

2022-12-12 04:14 UTC, n-rook commented on project/thscoreboard/replays/views/create_replay.py
>      replay_info = replay_parsing.Parse(bytes(temp_replay.replay))
👍

2022-12-12 04:14 UTC, n-rook commented on project/thscoreboard/replays/create_replay.py
> +        shot_instance = None
If you're happier with it this way that's fine too.

2022-12-12 04:14 UTC, n-rook approved these changes

2022-12-12 17:23 UTC, merged