Self host EB Garamond as well
n-rook/thscoreboard pull request #141
Opened 2022-12-12 16:42 UTC by 32th-System

It makes the font look slightly different now but I think I prefer it and it also makes it looks sharper

2022-12-12 17:23 UTC, n-rook requested changes
Looks good, thanks!

In the future, if there's an assigned GitHub issue open for something (like #92), please try to ask the person to whom its assigned before working on it. In this case it was fine, I hadn't done anything on EB Garamond so no effort was wasted. But I would have been sad if I had a PR that was 90% done.

This is part of why I try to file issues; it helps us not forget work we have to do, but it also helps prevent us from all writing the same code and accidentally wasting effort

2022-12-12 17:23 UTC, n-rook commented on project/thscoreboard/shared_content/static/fonts/fonts.css
> +
I think we should keep the two fonts in different files, just to make it easier to keep them straight.

(Actually, I just found out about "SASS modules" https://sass-lang.com/guide; we should definitely use those at some point so that all our files get compiled into one place. But no need to do that in this PR.)

2022-12-12 17:23 UTC, n-rook commented on project/thscoreboard/shared_content/static/fonts/fonts.css
> +    src: url('EBGaramond-Bold.woff2') format('woff2');
wtf there are two EB Garamonds

I had a whole comment written out going "where did you find these, the garamond I found is only two files??" before I figured it out

(no action required)

In the medium term, since this version has real bolds, we should stop using meme font weights like 550 and use only the widths defined here

2022-12-12 17:23 UTC, n-rook commented on project/thscoreboard/replays/templates/replays/docs/licenses.html
> +        We use the fonts <a href="https://www.latofonts.com/">Lato</a> and <a href="https://github.com/octaviopardo/EBGaramond12">EB Garamond 12</a>, both of which are licensed under the <a href="htt
I think we should keep explicitly giving credit to the font creators in this file. It's just a nice thing to do.

Actually, I'd like to add a credits page so we give credit to ourselves too. Someday...

2022-12-12 17:23 UTC, n-rook commented on project/thscoreboard/shared_content/static/fonts/fonts.css
> +@font-face {
Please sort the @font-face tags by weight, so it's easy to check and make sure we didn't forget any.

2022-12-12 18:17 UTC, 32th-System commented on project/thscoreboard/replays/templates/replays/docs/licenses.html
> +        We use the fonts <a href="https://www.latofonts.com/">Lato</a> and <a href="https://github.com/octaviopardo/EBGaramond12">EB Garamond 12</a>, both of which are licensed under the <a href="htt
It doesn't have to be someday

2022-12-12 21:22 UTC, n-rook requested changes
thanks, this is basically ready

2022-12-12 21:22 UTC, n-rook commented on project/thscoreboard/replays/templates/replays/docs/licenses.html
> +        We use the fonts <a href="https://www.latofonts.com/">Lato</a> and <a href="https://github.com/octaviopardo/EBGaramond12">EB Garamond 12</a>, both of which are licensed under the <a href="htt
You didn't put back the Lato guy's name! That's what I meant when I said "keep explicitly giving credit to the font creators".

2022-12-12 21:25 UTC, 32th-System commented on project/thscoreboard/replays/templates/replays/docs/licenses.html
> +        We use the fonts <a href="https://www.latofonts.com/">Lato</a> and <a href="https://github.com/octaviopardo/EBGaramond12">EB Garamond 12</a>, both of which are licensed under the <a href="htt
It's in credits.html

2022-12-13 00:34 UTC, n-rook approved these changes

2022-12-13 00:34 UTC, merged