support spell practice
n-rook/thscoreboard pull request #148
Opened 2022-12-16 07:09 UTC by raviddog

add detection and ui (spell card id) for spell practice replays (currently only TH08)

2022-12-17 00:32 UTC, n-rook requested changes
Looks good, but I have a few pain in the ass comments for extra stuff we should do before letting people upload spell practice replays

2022-12-17 00:32 UTC, n-rook commented on project/thscoreboard/replays/templates/replays/replay_details.html
> +            {% if replay.spell_card_id %}
I think in addition to this, we should also show the spell card ID on the "publish replay" page that shows up when you have already uploaded the replay but get the chance to add a comment or something like that.

2022-12-17 00:32 UTC, n-rook commented on project/thscoreboard/replays/templates/replays/replay_details.html
> +            {% if replay.spell_card_id %}
I think we should change some of the lists too, if we are going to include spell practice replays. Some of the lists should not have spell practice. Other lists should, but they should be marked so that they're easily distinguished by run. I think the difficulty page (like https://www.silentselene.net/replays/th06/d2) and the difficulty+shot page (https://www.silentselene.net/replays/th06/d2/ReimuA) should probably not have spell practice replays, since they really should be functioning as scoreboards. But they should definitely show up on the front page since that's telling people about every new upload.

2022-12-18 10:05 UTC, raviddog commented on project/thscoreboard/replays/templates/replays/replay_details.html
> +            {% if replay.spell_card_id %}
I think we'll want to reorganise these pages at some point in the future, make it easier to navigate, etc
But for now, I've excluded non-Regular (detected as full run) replays from those pages

2022-12-18 10:42 UTC, raviddog commented on project/thscoreboard/replays/models.py
> +
I think I've done this. I added a spell practice replay to the db saving tests, I'm not sure how to test violating the constraints though

2022-12-18 20:17 UTC, n-rook requested changes

2022-12-18 20:17 UTC, n-rook commented on project/thscoreboard/replays/views/create_replay.py
> +        'replayType': game_ids.GetReplayType(replay_info.replayType)
nitpick: let's call this replay_type, not replayType, for consistency with the other context variables

2022-12-18 20:17 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +
I think that should work, yeah. For a test, you can add something to test_models that creates a spell practice replay, and then try to set its replay_type field to normal and save it, and then check that this raises an exception.

2022-12-18 20:17 UTC, n-rook commented on project/thscoreboard/replays/views/replay_list.py
> +        .filter(replay_type=1)
We should try to avoid magic numbers in regular code where we can; there is no way we're going to remember what 1, 2, and 3 are all the time. I think you should be able to do something like `models.ReplayType.REGULAR`. I'm not sure if there's a good way to do it in places where you don't really want to be importing `models`, so I didn't leave any comments there.

2022-12-18 20:17 UTC, n-rook commented on project/thscoreboard/replays/views/view_replay.py
> +        'replayType': game_ids.GetReplayType(replay_instance.replay_type)
as above, we should prefer to camel-case this

2022-12-18 20:17 UTC, n-rook commented on project/thscoreboard/replays/views/view_replay.py
> +        'spell_name': spell_cards.get_spell_name('en', game_id, replay_instance.spell_card_id, replay_instance.difficulty),
We should add a function on the replay model itself to do this, kind of like GetDifficultyName(). If a function has no arguments (which should be possible if we use [get_language](https://docs.djangoproject.com/en/4.1/ref/utils/#django.utils.translation.get_language)) we don't even need to call it here, we can just pass replay_instance in and call it from the template.

2022-12-19 01:38 UTC, raviddog commented on project/thscoreboard/replays/views/view_replay.py
> +        'replayType': game_ids.GetReplayType(replay_instance.replay_type)
its hard because the naming standard in the DB is with underscores, but the naming standard in the dataclass is camelcase, so I'm not sure how to handle this

2022-12-19 01:39 UTC, raviddog commented on project/thscoreboard/replays/views/view_replay.py
> +        'replayType': game_ids.GetReplayType(replay_instance.replay_type)
oh nvm I see what you're saying

2022-12-19 09:41 UTC, 32th-System requested changes
Spell IDs in spells.js aka spells/{lang}/{game_id},json and in all the code I wrote around it are also 0 indexed

2022-12-19 13:59 UTC, raviddog commented
I have created another branch retaining the spell card name changes
https://github.com/raviddog/thscoreboard/tree/spell-practice-name-backup

2022-12-20 20:59 UTC, 32th-System commented on project/thscoreboard/replays/management/commands/download_thpatch_spells.py
> +from django.core.management.base import BaseCommand
On the one hand, deleting this file would defeat the whole point of the spell name code, on the other hand, we weren't supposed to implement spell names in the same PR. I'll get rid of it and the Japanese th08.json

2022-12-20 23:34 UTC, n-rook commented on project/thscoreboard/replays/management/commands/download_thpatch_spells.py
> +from django.core.management.base import BaseCommand
yeah I'm not saying there's anything wrong with the file or that it shouldn't go in later, but it only makes sense with the other spell name stuff we are doing in the next PR

2022-12-20 23:35 UTC, 32th-System commented on project/thscoreboard/replays/management/commands/download_thpatch_spells.py
> +from django.core.management.base import BaseCommand
Looks like it's all gone now

2022-12-21 04:59 UTC, raviddog commented on project/thscoreboard/replays/views/view_replay.py
> +        replay_instance.spell_card_id += 1
Added to both the model and the Replay object in ReplayParsing.py, although the naming conventions of both are different, so the calls in the create_replay template and the replay_details template are different. Hopefully this is okay

2022-12-21 05:01 UTC, n-rook commented on project/thscoreboard/replays/views/view_replay.py
> +        replay_instance.spell_card_id += 1
eh this is the other benefit of a linter. if flake8 doesn't complain about something like that, I won't either

2022-12-21 05:01 UTC, n-rook approved these changes

2022-12-21 12:59 UTC, 32th-System approved these changes

2022-12-22 01:04 UTC, merged