Consistent stage splits
n-rook/thscoreboard pull request #163
Opened 2022-12-22 11:44 UTC by raviddog

fixes #60

2022-12-22 20:50 UTC, n-rook requested changes
Thanks for sending this so quickly!

2022-12-22 20:50 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +    score = models.BigIntegerField(blank=True, null=True)
Add a note explaining why this is not set sometimes. After all, we thought it would be set all the time, so it would not be too surprising if we forgot about it later.

2022-12-22 20:50 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +    """adjust stage data to be end-of-stage"""
Python nitpick: `""" """` should only be used for _docstrings_; that is, strings put immediately after a function, class, or field and used as documentation. This is a regular code comment, so you should use `#`.

2022-12-22 20:50 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +    for i in range(len(rep_stages)):
I think this two-step process is more confusing than it needs to be. We first record the stage values wrong (above), and then we fix them here. Instead, I think it would be clearer to get them right the first time. To be honest, this code is always going to be a bit confusing, because what ZUN did makes no sense, but I think that approach would be clearer.

This would probably look something like:
```
for i, this_stage in enumerate(replay.stages):
  if replay.file_header.stage_offsets[i] != 0:
    if i + 1 >= len(replay.stages):
      next_stage = None
    else:
      next_stage = replay.stages[i + 1]
    
    s = ReplayStage()
    s.stage = i
    s.score = score.score * 10
    # …
    if next_stage:
      s.power = next_stage.power
      # ...
    else:
      s.power = None
      # ...
```

If you hate this idea, let me know, but I really do think it would be clearer. This applies to the other bug fixes too.

2022-12-22 20:50 UTC, n-rook commented on project/thscoreboard/replays/game_fields.py
>  def GetFormatLives(game_id: str, lives: int, life_pieces: int) -> str:
Fix this function (and the other ones) so that they ask for Optional[int], not int.

If you're wondering why the heck these annotations exist at all, there actually are Python type checkers, I just haven't figured out how to set one up yet.

2022-12-22 20:50 UTC, n-rook commented on project/thscoreboard/replays/game_fields.py
> +def FormatStages(game_id: str, replay_stages):
If I saw this function get called, it would be very surprising to me that it actually modified the replay_stages argument! In general I don't think we should ever modify database model instances unless we actually plan on saving those changes to the database. Otherwise it just gets too confusing to figure out what is going on with an object, since its values and behavior will be totally different from what the documentation on the model says.

In this case we have a few alternatives. I don't love any of them but I think they would all work.

1. Use [default_if_none](https://stackoverflow.com/questions/16459890/django-template-display-item-value-or-empty-string) in the template. In some sense this is "good style", since we are deciding how to display the empty value in the template itself. But it seems very repetitive. I think I would actually do this if I were writing the PR but I can see why you wouldn't want to.
2. Define a new dataclass here, called something like "DisplayStage". Instead of modifying replay_stages, create a DisplayStage for each stage and return that list instead.
3. Add lots of properties on the model; "display_power", "display_score" etc.

Let me know if you hate all of these and I will try to think of something else… don't quit the project :lesanae:

2022-12-23 05:09 UTC, raviddog commented on project/thscoreboard/replays/replay_parsing.py
> +    for i in range(len(rep_stages)):
I tried doing that, but it looked horrible. I had to add way more bounds checks and basically ended up parsing each stage twice. I reckon this way is clearer because we separate out replay parsing bugs from the correction code, so it's more explicit what's happening.

2022-12-23 05:12 UTC, raviddog commented on project/thscoreboard/replays/game_fields.py
>  def GetFormatLives(game_id: str, lives: int, life_pieces: int) -> str:
I'm trying to think of a situation where life_pieces is not provided and yet we still want to use this function. A ReplayStage object will always have this field, even if its set to None, so we just need a None check on the value. If there is an object that doesn't have the life_pieces field, why would we need to call this function?

2022-12-23 05:14 UTC, raviddog commented on project/thscoreboard/replays/game_fields.py
> +def FormatStages(game_id: str, replay_stages):
My bad, it's a remnant from when I tried to use a loop to automate checking each field, but both the ReplayStage object and the model object didn't support that syntax so I ended up assigning them manually and forgot to apply the changes to a separate object instance.

2022-12-23 05:26 UTC, raviddog commented on project/thscoreboard/replays/replay_parsing.py
> +    for i in range(len(rep_stages)):
Also some games we add later will actually contain the end stage data, so I feel that it will be confusing if some of the parsers look like a nightmare and some don't.

2022-12-23 05:29 UTC, raviddog commented on project/thscoreboard/replays/replay_parsing.py
> +    for i in range(len(rep_stages)):
The advantage of this strategy is that all the values we parse are right next to each other, so it's very easy to see if we miss anything. I value that over shortening the code.

2022-12-23 22:19 UTC, n-rook requested changes

2022-12-23 22:19 UTC, n-rook commented on project/thscoreboard/replays/game_fields.py
>  def GetFormatLives(game_id: str, lives: int, life_pieces: int) -> str:
The reason I asked for `Optional[int]` is because you edited these functions to support `None`, like

```
if lives is None:
  return ""
```

I don't really have an opinion on whether they should accept None or not, but if they do, you should annotate the types correctly. And if they don't, we should delete that code.

2022-12-23 22:19 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +    for i in range(len(rep_stages)):
OK, if you've tried it and think it looks horrible, I'll believe you

2022-12-23 22:19 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +    for i in range(len(rep_stages)):
This would be closer to idiomatic Python if you did it like:

```
for i, this_stage in enumerate(rep_stages):
  if i < len(rep_stages - 1):
    next_stage = rep_stages[i]
    …
  else:
    …
```

rather than accessing rep_stages[i] and rep_stages[i+1] all the time. Please make that change everywhere else, too.

2022-12-23 22:19 UTC, n-rook commented on project/thscoreboard/replays/test_view_replay.py
> -    def testFields(self):
Hmm… Do we really want to get rid of this? I mean, this was for making sure we didn't forget to set game fields for various games, right?

Can we just edit this to not check the last stage for a replay, instead?

2022-12-24 06:33 UTC, raviddog commented on project/thscoreboard/replays/game_fields.py
>  def GetFormatLives(game_id: str, lives: int, life_pieces: int) -> str:
Does Optional mean it doesn't have to be that type, or does it mean the argument isnt necessary, because I was under the impression it was the latter, and I don't see us calling this function without all 3 arguments

2022-12-24 06:50 UTC, raviddog commented on project/thscoreboard/replays/game_fields.py
>  def GetFormatLives(game_id: str, lives: int, life_pieces: int) -> str:
I'll do it anyway if you think that's best

2022-12-24 17:57 UTC, n-rook approved these changes

2022-12-27 03:31 UTC, merged