Show spell names for spell practice replays
n-rook/thscoreboard pull request #164
Opened 2022-12-22 21:19 UTC by 32th-System

2022-12-23 22:34 UTC, n-rook requested changes
Nice!

2022-12-23 22:34 UTC, n-rook commented on project/thscoreboard/replays/spell_cards.py
> +                pass
These files should always be here, right? Should we log a warning if a file is missing?

2022-12-23 22:34 UTC, n-rook commented on project/thscoreboard/replays/spell_cards.py
> +    """Retrieves a spell card's name based on a language, the gameid of the game it's from, a 0 indexed spell ID, and a difficulty ID"""
Nitpick: Don't write a really long one line docstring; try to keep them under 80 characters. Instead do this on multiple lines. See https://peps.python.org/pep-0257/.

For this one, you are really just describing the arguments. So I would do something like this:

```
"""Retrieves a spell card's name.

Args:
  lang: A language code for the name.
  game_id: The game the spell card came from.
  spell_id: The spell card's ID (0-indexed).
  difficulty: The difficulty for the game.
"""
```

This is the Google argument documentation format (see https://google.github.io/styleguide/pyguide.html#383-functions-and-methods). I don't really care about requiring docs have this "Args:" section, but I just used it because it's convenient for this case and has all the information you put in the docstring anyway.

2022-12-23 22:34 UTC, n-rook commented on project/thscoreboard/replays/spell_cards.py
> +    for i in range(difficulty + 1):
I don't understand this for statement; what's going on here?

2022-12-23 22:34 UTC, n-rook commented on project/thscoreboard/replays/spell_cards.py
> +from replays import game_ids
This module needs tests!

2022-12-23 22:34 UTC, n-rook commented on project/thscoreboard/replays/spell_cards.py
> +    return None
Should we raise an exception if a spell name is not found?

2022-12-23 22:34 UTC, n-rook commented on project/thscoreboard/replays/management/commands/download_thpatch_spells.py
> +                os.makedirs(f'replays/spells/{lang}', exist_ok=True)
I think we should try to avoid putting generated, non-checked in files into the code directories like `replays/`. Especially, if we put the jp file (which is checked in) next to the en one (which is not checked in), it will get confusing.

Honestly it might just be best to check the en file in too (although we would still want this command obviously). That way it is easy to update without server access, and jp and en are handled in the same way.

2022-12-23 22:34 UTC, n-rook commented on project/thscoreboard/replays/templates/replays/publish.html
> +            {% elif replay.spell_card_id %}
IMO we can cut this part now. There should always be a spell name, right? Same with the replay_details file below.

2022-12-23 22:57 UTC, 32th-System commented on project/thscoreboard/replays/spell_cards.py
> +    for i in range(difficulty + 1):
it's to make sure `i` reaches `difficulty` because I want to check all IDs from `spell_id` to `spell_id - difficulty`

2022-12-25 21:28 UTC, 32th-System commented on project/thscoreboard/replays/spell_cards.py
> +    return None
I'm more in favour of just displaying the ID on the site

2022-12-25 21:29 UTC, 32th-System commented on project/thscoreboard/replays/templates/replays/publish.html
> +            {% elif replay.spell_card_id %}
If there is no spell name I still want to indicate that the replay is spell practice and show the spell ID as a backup

2022-12-26 18:19 UTC, n-rook approved these changes

2022-12-26 18:19 UTC, n-rook commented on project/thscoreboard/replays/test_spell_name.py
> +import unittest
For tests, I think it's best to always name them test_the_name_of_the_module_they_are_testing, so it is easy to find them. For example this file should be test_spell_cards.

(Actually I think the best way would really be to call them like "spell_cards_test", so they would appear next to the module being tested when the directory is sorted alphabetically, but unfortunately the default Django test finder doesn't support that format. Maybe I'll mess around with it someday)

2022-12-26 18:19 UTC, n-rook commented on project/thscoreboard/replays/spell_cards.py
> +    for i in range(difficulty + 1):
Could you add a comment to that effect?

2022-12-26 18:19 UTC, n-rook commented on project/thscoreboard/replays/spell_cards.py
> +    return None
IMO it'd be better to return 500— I'm a strong believer in [offensive programming](https://wiki.c2.com/?OffensiveProgramming)— but I won't insist

2023-02-08 19:45 UTC, closed without merging