Add IP bans with subnet support
n-rook/thscoreboard pull request #168
Opened 2022-12-25 17:59 UTC by 32th-System

2022-12-26 18:31 UTC, n-rook requested changes
Thanks for finishing this off

2022-12-26 18:31 UTC, n-rook commented on project/thscoreboard/users/other_views.py
> +            request_ip = ip_address(request.META.get('REMOTE_ADDR'))
Rather than checking from within register(), I think it would be better to create a decorator that rejects a request if the user is IP banned. That way, it will be easy to reuse the same code for other routes, and it allows us to keep the view functions simpler. The downside is that this approach makes the error uglier, but I think that's fine.

This is conceptually similar to the [builtin decorators](https://docs.djangoproject.com/en/4.1/topics/http/decorators/), so you can take a look at them if you are not sure how to implement it.

2022-12-26 18:31 UTC, n-rook commented on project/thscoreboard/users/models.py
> +        ipaddress.ip_network(self.ip)
I am assuming you are doing this to make sure the IP addresses are valid, right? If that's the case, I think it would be better to implement it as a [validator](https://docs.djangoproject.com/en/4.1/ref/validators/).

2022-12-26 18:31 UTC, n-rook commented on project/thscoreboard/users/models.py
> +
IMO we should have a comment field here too, explaining why some IP is banned. Maybe an author field saying who banned them too if you can figure out a good way to set that

2022-12-27 21:07 UTC, n-rook approved these changes

2022-12-27 21:07 UTC, n-rook commented on project/thscoreboard/users/other_views.py
> +    def is_ip_banned(ip_to_check: str):
nit: I don't think there's any reason for this to be a closure, so I would define it externally as a private function (that is, a function with a single underscore in front)

2022-12-27 21:11 UTC, 32th-System commented on project/thscoreboard/users/other_views.py
> +    def is_ip_banned(ip_to_check: str):
I mainly put it there specifically so that the function is only available in the scope of the function that needs this functionality. It's more about scope for me

2022-12-27 21:12 UTC, n-rook commented on project/thscoreboard/users/other_views.py
> +    def is_ip_banned(ip_to_check: str):
that's not how I would do it but I don't have anything against it either as an idea, it's just a matter of taste. so that's fine

2022-12-27 21:25 UTC, merged