th12
n-rook/thscoreboard pull request #175
Opened 2022-12-31 06:34 UTC by raviddog

2022-12-31 17:33 UTC, n-rook requested changes
Looks basically good, just a few minor comments

2022-12-31 17:33 UTC, n-rook commented on project/thscoreboard/replays/game_fields.py
> +_bomb_pieces = immutabledict({
Add a comment saying what this dict is

2022-12-31 17:33 UTC, n-rook commented on project/thscoreboard/replays/game_fields.py
> +    'th05': None,
We support th02-04 too, so we should specify them as well. (Or, alternatively, I think I'd be OK with only including the games with bomb pieces in them here, and calling `_bomb_pieces.get(game_id, None)` instead.)

2022-12-31 17:33 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +        #   fix zun fuckery
lol

2022-12-31 17:33 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +        r_type = game_ids.ReplayTypes.STAGE_PRACTICE
I think if we're going to detect stage practice, we need a test that's stage practice, just to check.

2023-01-04 03:29 UTC, raviddog commented on project/thscoreboard/replays/game_fields.py
> +    'th05': None,
games that don't include stage splits shouldn't ever be called in here, though theres no harm in it so i guess ill put em all in

2023-01-04 03:33 UTC, raviddog commented on project/thscoreboard/replays/replay_parsing.py
> +        r_type = game_ids.ReplayTypes.STAGE_PRACTICE
theres already one, test_replay_parsing.py line 195

2023-01-04 11:05 UTC, raviddog commented
wait why do these tests fail it works on my local branch

2023-01-04 11:27 UTC, raviddog commented
the more i fiddle with this the more it breaks

2023-01-04 15:16 UTC, n-rook requested changes

2023-01-04 15:16 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +        r_type = game_ids.ReplayTypes.STAGE_PRACTICE
I mean a test that actually tests this code in particular; that is, a test for UFO stage practice

2023-01-04 15:16 UTC, n-rook commented on project/thscoreboard/replays/test_replay_parsing.py
> +        self.assertEqual(r.replay_type, game_ids.ReplayTypes.REGULAR)
this is way easier to read btw, thanks for doing this

2023-01-04 15:17 UTC, n-rook commented
python datetimes can be really crazy and even half of professional developers don't know how to handle them right. basically the best thing to do is to make everything an "aware datetime" by passing in a timezone immediately, because otherwise some library operations will assume the datetime represents local time. this tends to manifest as tests failing on github but passing locally (or the other way around) because the test env on github is UTC but your local pc probably isn't. fortunately it seems to be fine now

2023-01-07 16:39 UTC, n-rook approved these changes

2023-01-09 02:44 UTC, merged