add slowdown to display+parsing
n-rook/thscoreboard pull request #186
Opened 2023-01-11 06:31 UTC by raviddog

how do i test a float

2023-01-11 06:32 UTC, raviddog commented
fixes #174

2023-01-11 21:41 UTC, n-rook requested changes
Add at least one test, please!

2023-01-11 21:41 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +    """Slowdown percentage in the replay"""
Specify the range in the comment. (In other words does it go from 0 to 1, or from 0 to 100?)

2023-01-16 15:47 UTC, n-rook approved these changes

2023-01-18 15:07 UTC, merged