make all replay stages 0-indexed
n-rook/thscoreboard pull request #258
Opened 2023-02-16 17:45 UTC by jgdhs27

lol

also, changed `GetFormatStage` so that extra stages are formatted as "Extra" instead of "7"

2023-02-17 02:44 UTC, n-rook requested changes
It looks like you need to update your branch to include the latest changes from the main branch, `nrook:main`. iirc you can do this by checking out your branch, running `git fetch` to fetch the latest remote changes, and then running `git merge nrook/main`

2023-02-17 02:44 UTC, n-rook commented on project/thscoreboard/replays/game_fields.py
> +    format_ex = 'Extra'
Since this is a constant, we should declare it at the top-level in all caps, like `_EXTRA_NAME`. If it is declared as a local variable like this, I expect it to change, so I get surprised when it doesn't change.

2023-02-17 02:44 UTC, n-rook commented on project/thscoreboard/replays/game_fields.py
> +    format_ex = 'Extra'
Could you upload a screenshot of what this looks like in practice? I'm worried "Extra" will take up too much room on the table compared to just numbers, so maybe "Ex" would be better. But I'm not sure, so I'd like to see it.

2023-02-17 02:44 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +    stages: List[ReplayStage] = dataclasses.field(default_factory=list)
It's better to use the lowercase ones; see https://peps.python.org/pep-0585/.

2023-02-17 04:35 UTC, raviddog commented on project/thscoreboard/replays/game_fields.py
> +    format_ex = 'Extra'
would it suffice to declare it right above the function? since it's only being used here I wouldn't want it to be too far away

2023-02-17 04:41 UTC, raviddog commented on project/thscoreboard/replays/game_fields.py
> +    format_ex = 'Extra'
While we're doing this it would be nice to have Phantasm as well, I guess it could be "Ph" and then we could use "Ex"
I think add an optional difficulty argument to the function to achieve this

2023-02-17 04:48 UTC, raviddog commented
fixes #181

2023-02-17 05:46 UTC, n-rook commented on project/thscoreboard/replays/game_fields.py
> +    format_ex = 'Extra'
Yes, that would be fine

2023-02-17 18:56 UTC, jgdhs27 commented on project/thscoreboard/replays/game_fields.py
> +    format_ex = 'Extra'
wasnt too sure since the constant is only use right here. ill follow raviddog's suggestion

2023-02-17 19:13 UTC, jgdhs27 commented on project/thscoreboard/replays/game_fields.py
> +    format_ex = 'Extra'
> While we're doing this it would be nice to have Phantasm as well, I guess it could be "Ph" and then we could use "Ex" I think add an optional difficulty argument to the function to achieve this

I completely forgot phantasm existed. added.

2023-02-17 19:14 UTC, jgdhs27 commented on project/thscoreboard/replays/replay_parsing.py
> +    stages: List[ReplayStage] = dataclasses.field(default_factory=list)
oh cool didnt know that. ive always used `List` but im on an older python, looks like its changed.

2023-02-17 19:15 UTC, jgdhs27 commented
merging with the "0-index" commit reverted a lot of my changes. fixed it by hand, hopefully didnt miss anything, tests are green at least

2023-02-17 19:50 UTC, jgdhs27 commented on project/thscoreboard/replays/game_fields.py
> +    format_ex = 'Extra'
![image](https://user-images.githubusercontent.com/44336657/219776672-5536880c-1851-4503-8a1b-7d0fbe2c937e.png)
looks good to me

2023-02-17 20:24 UTC, jgdhs27 commented
In order to display Ph properly, I needed to give it a distinct stage number. Previously, ex and ph both had stage number 7. I changed it so that ex has 7 and ph has 8. Feels like a bugfix.

2023-02-18 00:12 UTC, raviddog approved these changes

2023-02-18 15:43 UTC, n-rook approved these changes

2023-02-18 18:53 UTC, merged