Parse th15-th18
n-rook/thscoreboard pull request #261
Opened 2023-02-18 22:42 UTC by jgdhs27

2023-02-18 23:58 UTC, n-rook requested changes
I think this PR is way too big to review! In my experience, the difficulty of actually giving a good review that can catch issues scales about O(n^2) with the size of the review diff. And the diff here is something like 800 lines (not counting the generated code which doesn't count because I don't need to review it). At the very least, refactoring the existing replay parsing code and adding new games needs to be in separate PRs.

Of course, the downside of smaller reviews is that it adds to the time to get a change in. I have used "stacked PRs" before to fix this, where my first PR targets the main branch, but the second PR targets the first branch. (And then I never merge the second PR before the first one, I just wait for the first one to be approved.) This can be confusing but it's up to you if you want to use it. (Well, really I don't think the different changes here depend on each other anyway.)

2023-02-18 23:58 UTC, n-rook commented on project/thscoreboard/replays/kaitai_parsers/th06.py
> +        self.file_header = Th06.FileHeader(self._io, self, self._root)
This seems like it doesn't belong in this PR

2023-02-18 23:58 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +            # The end-of-stage data does not add the stage's clear bonus.
Huh, is this only the case in UM and not in other games in the same era?

2023-02-18 23:58 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +    for (i, current_stage), (j, next_stage) in zip(
I do like this refactoring, it looks much cleaner this way to me.

2023-02-18 23:58 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +def _Parse15(rep_raw) -> ReplayInfo:
This is optional, but have you thought about trying to reuse some of the code between the different games? I know I've heard that the newer games all have similar structures in the replays (as opposed to the older games which do weird stuff), so it seems like maybe it would be possible. And it'd make it easier to add new data parsing features later.

2023-02-19 00:01 UTC, 32th-System commented on project/thscoreboard/replays/replay_parsing.py
> +def _Parse15(rep_raw) -> ReplayInfo:
they are similair but the finer layout of the structs does change between every game and it's easier to just spell it out again. There is some reuse though with the th_modern struct

2023-02-19 00:04 UTC, raviddog commented on project/thscoreboard/replays/replay_parsing.py
> +    for (i, current_stage), (j, next_stage) in zip(
Agree, this is much nicer than my mess

2023-02-19 00:05 UTC, raviddog commented on project/thscoreboard/replays/replay_parsing.py
> +def _Parse15(rep_raw) -> ReplayInfo:
It would be possible I think, and we can look into it later but for now each game has enough of its own oddities that we should focus on functionality first, getting everything up and running

2023-02-19 00:33 UTC, raviddog requested changes
Apart from the typo, everything looks good

Theres a couple things you can add but they're not necessary in this PR and we can do them later. If you choose to do them later, open an issue so we don't forget.

- th16, th17 and th18 have spell practice, checks for these aren't present
- there are some game specific fields that haven't been parsed
  - th16 season
  - th17 tokens and hyper bar
  - th18 cards
  - The latter two here need some additional groundwork done for their implementation, so I feel they can be left separately

Other than that, if everything else looks good on your end then we're good to go

2023-02-19 00:33 UTC, raviddog commented on project/thscoreboard/replays/game_fields.py
> +    'th16': _table_fields_th12,
typo here :)

2023-02-19 00:36 UTC, raviddog commented on project/thscoreboard/replays/replay_parsing.py
> +            # The end-of-stage data does not add the stage's clear bonus.
UM is the first game to have end-of-stage data so this problem can't occur in previous games

(I originally made this comment then misread the code and deleted it)

2023-02-19 15:44 UTC, jgdhs27 commented on project/thscoreboard/replays/replay_parsing.py
> +def _Parse15(rep_raw) -> ReplayInfo:
I agree with 32th here, while there is a lot of overlap, each struct is subtly different.

2023-02-19 15:45 UTC, jgdhs27 commented on project/thscoreboard/replays/kaitai_parsers/th06.py
> +        self.file_header = Th06.FileHeader(self._io, self, self._root)
yeah, i can make a separate PR for that one

2023-02-19 15:52 UTC, jgdhs27 commented on project/thscoreboard/replays/game_fields.py
> +    'th16': _table_fields_th12,
fixed

2023-02-19 16:16 UTC, raviddog approved these changes
Awesome

2023-02-19 16:39 UTC, jgdhs27 commented
added a field for th16 season power

2023-02-19 17:49 UTC, n-rook commented
Yeah from what I can tell this looks good. Split the refactoring into a separate PR (from what I can tell this should be easy, since it's split into different commits anyway) and it'll be good to go

2023-02-19 20:45 UTC, jgdhs27 commented
Rebased + added spell practice parsing

2023-02-19 20:47 UTC, n-rook approved these changes
Looks great, thanks for all this!

2023-02-20 07:18 UTC, merged