Show spell card names on spell practice replays
n-rook/thscoreboard pull request #267
Opened 2023-02-19 20:04 UTC by 32th-System

2023-02-19 20:35 UTC, n-rook requested changes
Looks great; only minor comments

(Also I freaked out because I saw a 1000 line diff before I realized why it was so long lol)

2023-02-19 20:35 UTC, n-rook commented on project/thscoreboard/replays/spell_names.py
> +    'th08': tuple([
Instead of `tuple([a, b, c])` you can just do `(a, b, c)`

2023-02-19 20:35 UTC, n-rook commented on project/thscoreboard/replays/spell_names.py
> +def get(game_id: str, spell_id: int):
Add a docstring

2023-02-19 20:35 UTC, n-rook commented on project/thscoreboard/replays/views/view_replay.py
> +        'spell_name': spell_names.get(game_id, replay_instance.spell_card_id),
opt: consider defining a GetSpellCardName() function on the replay model itself instead, I feel like that could be convenient to have around

2023-02-19 20:37 UTC, 32th-System commented on project/thscoreboard/replays/spell_names.py
> +    'th08': tuple([
```
C:\Users\thc>python
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> a = tuple("a", "b", "c")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: tuple expected at most 1 argument, got 3
```

2023-02-19 20:38 UTC, 32th-System commented on project/thscoreboard/replays/spell_names.py
> +    'th08': tuple([
oh you meant without the tuple keyword

2023-02-20 00:55 UTC, n-rook approved these changes

2023-02-20 00:58 UTC, merged