merge getformatlifepieces into getformatlives
n-rook/thscoreboard pull request #270
Opened 2023-02-20 08:48 UTC by raviddog

2023-02-20 13:45 UTC, n-rook requested changes
Looks good, just a few minor comments

2023-02-20 13:45 UTC, n-rook commented on project/thscoreboard/replays/game_fields.py
> +def GetFormatLives(game_id: str, lives: Optional[int], life_pieces: Optional[int], extends: Optional[int] = 0) -> str:
`-> Optional[str]`, right?

2023-02-20 13:45 UTC, n-rook commented on project/thscoreboard/replays/game_fields.py
> +    life_pieces_str = ""
You actually shouldn't need to declare these two variables up here like this. They're set in every code path anyway.

2023-02-20 13:45 UTC, n-rook commented on project/thscoreboard/replays/game_fields.py
> +    else:
Since you `return None` if lives is None, you don't need to put anything in an else clause. After all the whole rest of the function will only execute if lives is not None.

2023-02-20 13:45 UTC, n-rook commented on project/thscoreboard/replays/game_fields.py
> +def GetFormatLives(game_id: str, lives: Optional[int], life_pieces: Optional[int], extends: Optional[int] = 0) -> str:
Docstring plz

2023-02-20 13:51 UTC, raviddog commented on project/thscoreboard/replays/game_fields.py
> +    life_pieces_str = ""
I like having them here as kind of a clear "these are the strings I will be using" sort of thing

2023-02-21 17:05 UTC, n-rook approved these changes

2023-02-22 03:24 UTC, merged