Download replays according to ingame user replay filename format
n-rook/thscoreboard pull request #279
Opened 2023-02-22 23:47 UTC by 32th-System

2023-02-23 20:48 UTC, jgdhs27 requested changes

2023-02-23 20:48 UTC, jgdhs27 commented on project/thscoreboard/replays/models.py
> +        def numberToBase(n: int, b: str) -> str:
I found it very difficult to understand what this function does and what `b` is. I would prefer if it was just `numberToBase36`. ~~Also where are the unit tests that show that this code works~~

2023-02-24 18:59 UTC, jgdhs27 commented on project/thscoreboard/replays/test_game_ids.py
> +        self.assertEqual(game_ids.MakeReplayId(96), '002o')
I would really prefer `self.assertEqual(to_base_36(3 * 36 + 1), '0031')`. As it stands, this test doesn't explain itself and I have no idea why it should pass.

2023-02-24 19:21 UTC, jgdhs27 commented on project/thscoreboard/replays/test_game_ids.py
> +        self.assertEqual(game_ids.MakeReplayId(3 * 36 + 1), '0031')
I would strongly prefer if the function was called `to_base_36`. It explains what the function does, instead of just the context it's called in. When you call it with `rpy_id = to_base_36(self.id)` inside `GetNiceFilename` it's already clear what the goal was.
It also would let you write tests. Currently these tests just looks like "random number maps to random string". When I read these asserts I have no idea why they should be true and why you're testing for it.
(also, [snake_case for python functions](https://peps.python.org/pep-0008/#function-and-variable-names))

2023-02-24 19:31 UTC, 32th-System commented on project/thscoreboard/replays/test_game_ids.py
> +        self.assertEqual(game_ids.MakeReplayId(3 * 36 + 1), '0031')
where do you think I should put the function?

2023-02-24 19:33 UTC, jgdhs27 commented on project/thscoreboard/replays/test_game_ids.py
> +        self.assertEqual(game_ids.MakeReplayId(3 * 36 + 1), '0031')
would fit fine in models.py imo

2023-02-24 19:37 UTC, 32th-System commented on project/thscoreboard/replays/test_game_ids.py
> +        self.assertEqual(game_ids.MakeReplayId(3 * 36 + 1), '0031')
Or I could leave it where it is and name it `MakeBase36ReplayId`

2023-02-24 19:40 UTC, jgdhs27 commented on project/thscoreboard/replays/test_game_ids.py
> +        self.assertEqual(game_ids.MakeReplayId(3 * 36 + 1), '0031')
that works

2023-02-24 19:44 UTC, jgdhs27 approved these changes

2023-02-24 19:57 UTC, merged