prevent duplicate replays from being submitted
n-rook/thscoreboard pull request #287
Opened 2023-03-09 12:30 UTC by raviddog

fixes #77 

scenarios:
1. attempt to upload a duplicate replay > validation error on replays/upload
2. proceed to publish page on both replays > submit one > attempt to submit second > i dont know how to add an error message to the form yet

2023-03-09 13:02 UTC, raviddog commented
wait i don't actually need the code for scenario 2 because the publish url wont exist anymore once the temp replay is gone

2023-03-10 00:37 UTC, n-rook requested changes
Nice, this'll be really good to have

2023-03-10 00:37 UTC, n-rook commented on project/thscoreboard/replays/views/create_replay.py
> +    hash = hashlib.sha256(replay_bytes).digest()
We should only have the code `hashlib.sha256(replay_bytes).digest()` in one place in the database. (Well, two places, it's fine to repeat it in the migration file.) That way there's no chance of a bug later if someone forgets what the right hash function is.

I would probably put the function in models.py... but I'm not really sure that's the right place. It would be fine to put it in a new module instead. (I don't think any of the existing modules are really the right place for it.)

2023-03-10 00:37 UTC, n-rook commented on project/thscoreboard/replays/views/create_replay.py
> +            # I don't know a better way of doing this right now
I think I actually have a good idea here. Take a look at the django docs:

https://docs.djangoproject.com/en/4.1/ref/forms/api/#django.forms.Form.non_field_errors

Apparently if you call [Form.add_error(None, "...")](https://docs.djangoproject.com/en/4.1/ref/forms/api/#django.forms.Form.add_error) then the error will be recorded on the form as a "non-field error". Then I think it'll show up as an error on the form; you can see `{{ form.non_field_errors }}` in publish.html.

2023-03-10 00:37 UTC, n-rook commented on project/thscoreboard/replays/views/create_replay.py
> +    duplicate = models.ReplayFile.objects.filter(replay_hash=hash)
If you felt clever you could add this as a method on the ReplayFile manager, like the visible_to function that exists now. But you don't have to.

2023-03-10 05:45 UTC, raviddog commented on project/thscoreboard/replays/views/create_replay.py
> +            # I don't know a better way of doing this right now
I'm thinking some sort of redirect actually is the corrent play here, because the pending replay no longer exists so the url the user is on is actually invalid. I'm just concerned the standard 404 doesn't explain what happened well enough.

2023-03-10 09:20 UTC, raviddog commented on project/thscoreboard/replays/views/create_replay.py
> +    duplicate = models.ReplayFile.objects.filter(replay_hash=hash)
I could, but every time a duplicate needs to be checked, we haven't actually created the ReplayFile object yet, so it wouldn't do anything currently.

2023-03-11 17:07 UTC, n-rook requested changes

2023-03-11 17:07 UTC, n-rook commented on project/thscoreboard/replays/constant_helpers.py
> +    hash = hashlib.sha256(file).digest()
This is duplicated code; just call CalculateReplayFileHash() below

2023-03-11 17:07 UTC, n-rook commented on project/thscoreboard/replays/views/create_replay.py
> +            # I don't know a better way of doing this right now
Oh, I see what you mean. In that case, I think what you really want is a totally different-looking page that's an error page, right? For that, you can create a totally new template to render (probably inheriting from the simple centered template base, since it doesn't have to be complicated), and just say exactly what you want there. I think it's better to not do a real URL redirect, since the appropriate URL for the page really is the "finish publishing" URL, we just want to render a different page there that says "this replay was already uploaded". This also makes it easy for you to put a link on that page to the actual replay.

2023-03-12 06:22 UTC, raviddog commented on project/thscoreboard/replays/views/create_replay.py
> +            # I don't know a better way of doing this right now
I think the 404 will have to do because the user can't even get to the code again coz the URL doesn't exist and I'm not really fond of the idea of leaving the row in the db even though the replay is already published just to forward requests.

2023-03-12 16:08 UTC, n-rook approved these changes

2023-03-16 06:31 UTC, merged