Import replays from royalflare
n-rook/thscoreboard pull request #304
Opened 2023-03-29 17:11 UTC by jgdhs27

Creates a new script called import_royalflare, which imports replays from royalflare. For instructions for how to use it, run `manage.py import_royalflare --help`.

To accommodate replays without a user, I made the "replay.user" field optional, and added a new field "replay.imported_username".

2023-03-31 04:52 UTC, 32th-System requested changes
I would recommend a constraint on the Replay model where the condition is basically ` imported_username__isnull=True ^ user__isnull=True` (^ is xor).

2023-03-31 04:52 UTC, 32th-System commented on project/thscoreboard/replays/management/commands/import_royalflare.py
> +        with open(json_file, encoding="utf-8") as f:
I think it would be better to specify files on the command line, instead of telling it to look at all files in an entire folder.

2023-03-31 12:08 UTC, 32th-System commented
Update: here's what the constraint looks like in Django code:
```python
            models.CheckConstraint(
                name="user_imported_username_xor_isnull",
                check=(
                    models.Q(user__isnull=True, imported_username__isnull=False)
                    | models.Q(user__isnull=False, imported_username__isnull=True)
                )
            ),
```

2023-03-31 17:45 UTC, jgdhs27 commented on project/thscoreboard/replays/management/commands/import_royalflare.py
> +        with open(json_file, encoding="utf-8") as f:
added it as an optional argument

2023-03-31 17:54 UTC, jgdhs27 commented
> I would recommend a constraint on the Replay model where the condition is basically ` imported_username__isnull=True ^ user__isnull=True` (^ is xor).

i agree with a need for a constraint, but idk if we should disallow both fields 

> Collaborator

added

2023-03-31 17:56 UTC, 32th-System commented
constraints are things enforced by the database itself and require a `makemigrations` and a `migrate`

2023-03-31 17:58 UTC, jgdhs27 commented
> constraints are things enforced by the database itself and require a `makemigrations` and a `migrate`

fixed 😅

2023-04-02 19:57 UTC, n-rook reviewed
This largely looks good. Submitting my review as a comment so you don't have to wait for my approval too.

We should think about how we want to display RF replays on the site, and how we should handle the possibility that a user will want to delete their old replays.

2023-04-02 19:57 UTC, n-rook commented on project/thscoreboard/replays/create_replay.py
> +    imported_username: Optional[str] = None,
Please update the docstring as well

2023-04-02 19:57 UTC, n-rook commented on project/thscoreboard/replays/replays_to_json.py
> +            else replay.imported_username or replay.name,
I think it's too much to expect from the frontend for it to handle a "User" json field that sometimes is an object and sometimes is a string. I'd rather have return "text" as the username in question and "url" be empty, and handle it appropriately from there.

2023-04-03 19:28 UTC, jgdhs27 commented on project/thscoreboard/replays/create_replay.py
> +    imported_username: Optional[str] = None,
done

2023-04-03 19:28 UTC, jgdhs27 commented on project/thscoreboard/replays/replays_to_json.py
> +            else replay.imported_username or replay.name,
I don't necessarily agree. for all fields, the frontend expects to get either a `string`, or a map `{'text' => string, 'url' => string}`. handling this doesn't add any logic to the frontend.

2023-04-03 19:44 UTC, 32th-System requested changes
Everything is fine, but I realized that you should also prettify the JSON files (or not have them at all)

2023-04-03 19:49 UTC, jgdhs27 commented
> Everything is fine, but I realized that you should also prettify the JSON files (or not have them at all)

done

2023-04-03 19:49 UTC, 32th-System approved these changes

2023-04-03 19:59 UTC, merged