Redesign
n-rook/thscoreboard pull request #306
Opened 2023-03-31 08:17 UTC by 32th-System

Design made by Nylilsa. This is just stage 1 of the redesign. Pretty much all pages will need adapting. In it's current state the site is functional, but only the front page is pretty.

2023-04-01 12:23 UTC, 32th-System commented
Current state:
https://www.youtube.com/watch?v=iTeCeMh4Tg0

2023-04-14 22:38 UTC, n-rook requested changes

2023-04-14 22:38 UTC, n-rook commented on project/thscoreboard/thscoreboard/templates/base.html
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
afaik this isn't relevant, see https://stackoverflow.com/questions/26346917/why-use-x-ua-compatible-ie-edge-anymore

2023-04-14 22:38 UTC, n-rook commented on project/thscoreboard/shared_content/static/style.css
> +*,
I've mentioned this in the discord before, but I'm against deleting the existing style sheets. I think we will lose a lot of formatting by accident and it makes it impossible to review this and tell what's actually changed. If you want, I can take a look tonight and tomorrow at changing this PR to do that.

2023-04-15 18:16 UTC, jgdhs27 commented on project/thscoreboard/replays/templates/replays/index.html
> +<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime tenetur cum voluptatum tempore atque optio consequuntur quos, quas, sint, recusandae eligendi odio. Animi consequatur placeat nemo d
we still need to figure out what to put here

2023-04-15 18:16 UTC, jgdhs27 commented on project/thscoreboard/replays/test_replays_to_json.py
> +        with override_settings(LANGUAGE_CODE="pt-br"):
what?

2023-04-15 21:22 UTC, 32th-System commented on project/thscoreboard/replays/test_replays_to_json.py
> +        with override_settings(LANGUAGE_CODE="pt-br"):
The function, because it uses gettext, doesn't always have to output the same thing. The test expects "th06", but if `compilemessages` was run, the function returns "EoSD" instead. To make sure that gettext doesn't affect anything, the function is run with a language we don't support. In another test that encounters issues with gettext, we use Brazilian Portugese, so I also use Brazilian Portugese here.

2023-04-15 21:44 UTC, jgdhs27 commented on project/thscoreboard/replays/test_replays_to_json.py
> +        with override_settings(LANGUAGE_CODE="pt-br"):
i see. in that case, i think it makes more sense to call `json_data = converter.convert_replays_to_serializable_list(replays)` in a real locale (eg. English) and check that it's converted correctly. After all, this is sent and to frontend and displayed, we want to check its display value is good.

2023-04-15 21:47 UTC, jgdhs27 commented on project/thscoreboard/replays/test_replays_to_json.py
> +        with override_settings(LANGUAGE_CODE="pt-br"):
i just saw the comment on the other usage and maybe that doesnt work in github CI? if thats the case, then please at least add a comment explaining that

2023-04-16 20:22 UTC, closed without merging