Add comments to replay tables
n-rook/thscoreboard pull request #318
Opened 2023-04-06 18:16 UTC by jgdhs27

Adds comments to replay tables. If the comment contains more than 250 characters, it is cut off and only the first 250 characters are shown. Also adds some small formatting changes to the table, to prevent certain entries (shot name, date) from wrapping and taking up muiltiple lines.

![image](https://user-images.githubusercontent.com/44336657/230461735-b881afa5-9a79-47de-aeff-a1aa34c2297f.png)

2023-04-10 23:37 UTC, n-rook requested changes

2023-04-10 23:37 UTC, n-rook commented on project/thscoreboard/shared_content/static/js/replays/replayTable.js
> +    cell.style.whiteSpace = "nowrap";
It's easier to understand HTML and make extra changes if we keep as much as possible to CSS. As such, we should put the "white-space: nowrap" in CSS, and here we should add a class to activate that CSS.

2023-04-10 23:37 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +        return self.comment[:limits.MAX_SHORTENED_COMMENT_LENGTH] + "..."
We need something like this, but in addition I think we should also still use "text-overflow: ellipsis" on the frontend. That'll be good for places like mobile where users likely have small screens.

2023-04-11 17:40 UTC, jgdhs27 commented on project/thscoreboard/shared_content/static/js/replays/replayTable.js
> +    cell.style.whiteSpace = "nowrap";
Added a new style  `.nowrap white-space: nowrap;` to `style.sass`

2023-04-11 17:47 UTC, jgdhs27 commented on project/thscoreboard/replays/models.py
> +        return self.comment[:limits.MAX_SHORTENED_COMMENT_LENGTH] + "..."
I actually want the text to be able to take up a couple of lines if needed

2023-04-11 23:48 UTC, n-rook approved these changes

2023-04-11 23:48 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +        return self.comment[:limits.MAX_SHORTENED_COMMENT_LENGTH] + "..."
Fair enough! I'm not sure about this, but I don't feel strongly enough to gainsay you about it.

2023-04-12 06:11 UTC, merged