Derive replay type from game
n-rook/thscoreboard pull request #320
Opened 2023-04-06 21:00 UTC by jgdhs27

Derive the replay type choices in the "Publish Replay Without File Form" from the game.

Currently, replays uploaded without file will always show all replay types, including PVP. This is a bug, as TH01, TH02, TH04 and TH05 do not support PVP.

Fixes #316

2023-04-06 21:05 UTC, jgdhs27 commented
Not sure why the test is failing. it passes with `python3.10 manage.py test -p test_forms.py`, but fails with `python3.10 manage.py test`.

2023-04-08 10:38 UTC, raviddog requested changes

2023-04-08 10:38 UTC, raviddog commented on project/thscoreboard/replays/forms.py
> +    games_with_pvp = [game_ids.GameIDs.TH03, game_ids.GameIDs.TH09]
I would recommend moving this array to game_fields.py

2023-04-08 15:17 UTC, jgdhs27 commented on project/thscoreboard/replays/forms.py
> +    games_with_pvp = [game_ids.GameIDs.TH03, game_ids.GameIDs.TH09]
done. although the data still feels a tiny bit out of place there.

2023-04-08 15:20 UTC, jgdhs27 commented
rebased onto main

2023-04-11 23:51 UTC, n-rook approved these changes

2023-04-12 21:50 UTC, raviddog approved these changes

2023-04-12 21:51 UTC, merged