Support th16 season as a field in Model.Shot
n-rook/thscoreboard pull request #328
Opened 2023-04-12 21:23 UTC by jgdhs27

Support th16 season as a field in Model.Shot. Allow the replay table to filter th16 replays by character and by season independently.

![image](https://user-images.githubusercontent.com/44336657/231588029-40e6117c-bb30-4d6c-841c-2dd4e3d1dd1e.png)

After this is approved we can try doing something similar for TH17 subshot, and maybe even TH08 route.

2023-04-12 23:22 UTC, n-rook requested changes

2023-04-12 23:22 UTC, n-rook commented on project/thscoreboard/replays/models.py
>      shot_id = models.TextField()
Hmm... I don't really like the idea of changing the database schema so that shot_id is no longer unique across a game. It seems like a big change to make, and a nice thing about the previous way of doing things was that it gave a unique name that roughly corresponded to how people talked about the shots. I'd rather see us add a season field, but retain the unique shot IDs, even if it's a little redundant.

2023-04-12 23:22 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +    th16_season_id = models.TextField(blank=True, null=True)
This concept is actually generic, IMO: I think we should use the same field to deal with th16 seasons and th17 animals. As such, I think a more generic field name is appropriate here; you don't actually have to implement it for wbawc in this PR, but we should leave the possibility open without further schema changes.

2023-04-12 23:22 UTC, n-rook commented on project/thscoreboard/replays/management/commands/setup_constant_tables.py
>      shots = [
This will cause issues in production, because _Create16() won't run. Unfortunately I think we have to add an update function in setup_constant_tables to do this right.

2023-04-12 23:22 UTC, n-rook commented on project/thscoreboard/replays/test_replays_to_json.py
> -            assert set(json_replay_data.keys()) == {
Why don't you think this assertion is necessary anymore?

2023-04-13 18:31 UTC, jgdhs27 commented on project/thscoreboard/replays/models.py
> +    th16_season_id = models.TextField(blank=True, null=True)
Godd point. I was thinking about this and we actually need to get a season and character for each shot for the frontend. (More generic: character + subshot). And while that could be implemented as two new redundant fields, I'm starting to think it makes more sense to just calculate them. I will try this approach.

2023-04-13 18:54 UTC, jgdhs27 commented on project/thscoreboard/replays/test_replays_to_json.py
> -            assert set(json_replay_data.keys()) == {
All keys are checked by value anyway

2023-04-13 19:14 UTC, jgdhs27 commented
Rewrote a few things so that the character and subshot, which are used in the frontend only, are now computed from the shot. This makes the change quite a bit smaller, and easier to adapt to other games (eg. TH17 with its subshots)

2023-04-13 19:16 UTC, jgdhs27 commented on project/thscoreboard/replays/management/commands/setup_constant_tables.py
>      shots = [
The newer implementation doesn't require any migrations

2023-04-13 22:19 UTC, 32th-System commented on project/thscoreboard/replays/models.py
> +    def GetCharacterame(self) -> str:
It seems like you typoed this name but you then just kept using the typoed name everywhere?

2023-04-14 05:47 UTC, jgdhs27 commented on project/thscoreboard/replays/models.py
> +    def GetCharacterame(self) -> str:
fixed

2023-04-14 22:21 UTC, n-rook approved these changes
Yeah, doing it before the database makes sense to me. At the very least, it has the positive effect of making it so that we don't have to worry about migrations.

2023-04-15 15:27 UTC, merged