Display route & filter by route in TH01/TH08
n-rook/thscoreboard pull request #331
Opened 2023-04-15 16:54 UTC by jgdhs27

![image](https://user-images.githubusercontent.com/44336657/232239217-b77cd11c-41cd-4dfb-9b3d-e118e2a4fea1.png)

2023-04-16 14:52 UTC, n-rook requested changes

2023-04-16 14:52 UTC, n-rook commented on project/thscoreboard/replays/replays_to_json.py
> +            route = replay.route
This logic feels too complicated for me. Can't we just do

```
if replay.route:
  json_dict["Route"] = replay.route.GetName()
```
?

2023-04-16 14:52 UTC, n-rook commented on project/thscoreboard/replays/views/replay_list.py
> +def _get_filter_options_th01(game: Game) -> dict[str, list[str]]:
I won't block submission for this, but in the medium term it would be nice to figure out a way to share more code between all these _get_filter-options functions, since they look very similar right now.

2023-04-16 14:57 UTC, jgdhs27 commented on project/thscoreboard/replays/replays_to_json.py
> +            route = replay.route
Unfortunately not as this would make `Route` the last column of the table

2023-04-16 15:15 UTC, jgdhs27 commented on project/thscoreboard/replays/replays_to_json.py
> +            route = replay.route
Disregard my last comment. The issue is that IN Ex replays have no route and therefore end up misaligned. Although that's caused by the fact that we just insert the json data directly into the table in the frontend, which is some code we can/should improve

2023-04-16 15:22 UTC, n-rook commented on project/thscoreboard/replays/replays_to_json.py
> +            route = replay.route
Ah, I see. In that case, I guess the game_id check is fine (although don't we need it for hrtp too?). Still, though, I think we should just do

```
if condition:
  json_dict['Route'] = ...
```

rather than setting `include_route` up here and then using it below.

2023-04-20 23:57 UTC, n-rook approved these changes

2023-04-21 05:51 UTC, merged