Add medal emojis to top 3 scores
n-rook/thscoreboard pull request #349
Opened 2023-04-23 16:38 UTC by jgdhs27

Add medal emojis (🥇, 🥈, 🥉) to the top 3 scores for a certain difficulty and shot.

![image](https://user-images.githubusercontent.com/44336657/233852541-f2f56dc3-2d91-4ab3-9a3d-634b3ec9f2ab.png)

In the future, I would like to add a player ranking by medal count, like royalflare had.

2023-04-23 17:02 UTC, n-rook requested changes

2023-04-23 17:02 UTC, n-rook commented on project/thscoreboard/replays/replays_to_json.py
>          replays: Iterable[models.Replay],
seems like we've introduced an undocumented requirement that replays be ordered (in reverse order) by score, no?

2023-04-23 19:01 UTC, jgdhs27 commented
Ok, I came up with another approach which adds the ranking inside the db query. I find this cleaner, I hope it addresses your concerns.

2023-04-23 19:03 UTC, jgdhs27 commented
Also, this makes it so that I could show the medals on the user page and front page without much difficulty, so I've done that.

2023-04-24 00:54 UTC, n-rook requested changes
Nice, this definitely looks like a good way to do it. Just one more comment

2023-04-24 00:54 UTC, n-rook commented on project/thscoreboard/replays/replays_to_json.py
> +) -> Manager[models.Replay]:
Could you move this function over to models.py? We may want in places that aren't returning json, but it'd be strange to import "replays_to_json" in a place where we aren't converting replays to json. Plus, looking at the signature, I think you can define this as a method on a custom manager, if I remember Django right. Certainly calling replays.objects.some_query().annotate_with_rank() would be very convenient.

2023-04-24 21:09 UTC, jgdhs27 commented on project/thscoreboard/replays/replays_to_json.py
> +) -> Manager[models.Replay]:
Done. Although I think the current implementation isnt perfect - I can only call `.annotate_with_rank()` on a `ReplayQuerySet` object but not a `ReplayManager` object, which feels wrong.

2023-04-24 21:12 UTC, jgdhs27 commented on project/thscoreboard/replays/replays_to_json.py
> +) -> Manager[models.Replay]:
disregard that, fixed that little issue too.

2023-04-24 21:13 UTC, jgdhs27 commented
Ok, another revision done. `annotate_with_rank` is now part of the `ReplayQuerySet` object, leading to much nicer code. Added tests to that. I also fixed a bug where TASes and irregular replays were counted in the rankings.

2023-04-24 21:59 UTC, n-rook approved these changes
Nice!

I'm _slightly_ worried about performance, but it's probably fine :)

2023-04-25 15:33 UTC, merged