Fix user page rankings
n-rook/thscoreboard pull request #360
Opened 2023-04-28 21:04 UTC by jgdhs27

Currently, we call `.annotate_with_rank().filter(user=user)` to try to get user replays ranked. This doesn't work though, as the rank will apply to the filtered replays. Not really sure why, I don't understand DB stuff.

As a workaround, store ranks for all replays in a python dict, then apply them to a filtered queryset. This is cringe. Performance dropped by about 200ms. I'm sure there's a better way but idk what it is.

2023-04-29 16:52 UTC, n-rook commented
This is too slow :/ Especially since if it's taking 200ms now, I bet the big-O answer will be even worse once we have more replays in the database. I'd rather see us just stop displaying ranks on pages other than the full scoreboard for now.

In the long term this problem does seem fixable; it should be possible to get the ranks of replays in a reasonable amount of time. Especially since we can clamp the big-O from both ends; we aren't fetching that many rows here, and in all cases we don't care about the ranks of anything but the top replays. But it might be tricky. These pages might be helpful in figuring out how to do it:

https://docs.djangoproject.com/en/4.2/topics/db/aggregation/#combining-multiple-aggregations
https://stackoverflow.com/questions/56567841/django-count-and-sum-annotations-interfere-with-each-other

Remember too that you can uncomment part of settings.py to log all SQL queries, which should make it clearer what's really going wrong.

2023-04-29 17:26 UTC, jgdhs27 commented
Thanks for the links. I will try again some time next week, but if I can't get it to work, I'll just remove the feature for now.

2023-04-29 22:38 UTC, n-rook commented
You can always disable it for now and come back later when you have time to figure it out, too

2023-05-02 20:27 UTC, jgdhs27 commented
Is using Django 4.2 an option? https://stackoverflow.com/questions/68289137/filtering-on-a-window-function-in-django

2023-05-02 23:59 UTC, n-rook commented
I don't see why not, if it works

2023-05-02 23:59 UTC, n-rook commented
However definitely do not use Django 4.2 in this PR; if it works, send that change alone as a separate PR, and then merge it in here

2023-08-02 18:15 UTC, jgdhs27 commented
I still haven't found a way to get this to work with just a DB query. I'm still using a python dict, but I tried to get better performance by adding only top-3 replays to the dict.

2023-08-05 18:41 UTC, n-rook reviewed
How fast is it now? I didn't import rf on my personal machine, so I don't have enough data to tell when I tried it myself.

2023-08-05 20:03 UTC, jgdhs27 commented
On my machine, this function went from 0.045s to 0.145s.

2023-08-06 15:02 UTC, n-rook commented
Okay, I think that's fine then. In reality doing it this way isn't really that much slower than doing it on the db side; the main disadvantage comparatively is that it's kinda hacky (since you'd have to redo the same logic on other pages)

2023-08-06 15:04 UTC, n-rook requested changes
This logic is complicated enough that I want a unit test for it. Could you extract the new code into a public function in some other module (or a new module), and then write a unit test for it? That'd make it easier to use it elsewhere too.

2023-08-06 16:12 UTC, jgdhs27 commented
Ok, I extracted it and added some tests

2023-08-06 16:15 UTC, n-rook approved these changes
Great!

2023-08-06 16:15 UTC, n-rook commented on project/thscoreboard/replays/test_rank_replays.py
> +            with patch(
nit: Rather than patching n times, I think it'd be simpler and faster to patch once and just set return_value in each loop iteration.

2023-08-06 16:17 UTC, jgdhs27 commented on project/thscoreboard/replays/test_rank_replays.py
> +            with patch(
oh so swap the order of the `for` and `with`? sure.

2023-08-06 16:23 UTC, merged