GZ compress replay response
n-rook/thscoreboard pull request #373
Opened 2023-05-02 17:39 UTC by jgdhs27

Use GZ to compress the json sent by the server. This reduces the amount of data sent by about 84%, or from 2.2MB to 350kB for IN.

2023-05-02 18:08 UTC, jgdhs27 commented
![image](https://user-images.githubusercontent.com/44336657/235748671-36c2847c-104f-4c3f-841d-041ef72aea16.png)
based on this chart, i think compression could reduce the time for "Comtent Download" by about 250ms.

I noticed also that the request API lets me choose the priority, and I set its priority to high. (Done in the second commit.) Considering that the connection was stalled for 540ms, I think there is a lot more room for improvement right there!

2023-05-02 23:59 UTC, n-rook requested changes

2023-05-02 23:59 UTC, n-rook commented on project/thscoreboard/shared_content/static/js/replays/replayTable.js
> +        '<p style="color: red;">Failed to load replays</p>';
If you keep putting style tags on HTML, I'm going to keep telling you to use CSS instead :p

In this case, I think the best thing to do would actually be to put this error in the real html template, hide it by default, and unhide it in JS when appropriate (by removing a class or something like that)

2023-05-02 23:59 UTC, n-rook commented on project/thscoreboard/shared_content/static/js/replays/replayTable.js
> +  fetch(requestUri, {
might be easier to call this as an async function and use await

2023-05-02 23:59 UTC, n-rook commented on project/thscoreboard/shared_content/static/js/replays/replayTable.js
> +      'Accept-Encoding': 'gzip'
don't think you should do this (or have to do this)--- browser will set Accept-Encoding for you

2023-05-02 23:59 UTC, n-rook commented on project/thscoreboard/replays/views/replay_list.py
> +    replays_json_compressed = gzip.compress(replays_json.encode("utf-8"), 5)
I don't think you should need to call compress() yourself--- we should use middleware for this. That way we can respond appropriately to the Accept-Encoding header of the request.

2023-05-03 17:24 UTC, jgdhs27 commented on project/thscoreboard/thscoreboard/settings.py
> +MIDDLEWARE = [
oops, fixed

2023-05-03 17:24 UTC, jgdhs27 commented on project/thscoreboard/shared_content/static/js/replays/replayTable.js
> +  fetch(requestUri, {
done

2023-05-03 17:24 UTC, jgdhs27 commented on project/thscoreboard/shared_content/static/js/replays/replayTable.js
> +      'Accept-Encoding': 'gzip'
you're right, removed it

2023-05-03 23:02 UTC, n-rook commented on project/thscoreboard/replays/views/replay_list.py
> +    replays_json_compressed = gzip.compress(replays_json.encode("utf-8"), 5)
I tried this, and I think GZipMiddleware should just do this automatically on its own. You might have to put it at the top of the middleware section (https://docs.djangoproject.com/en/4.2/ref/middleware/#module-django.middleware.gzip).

It's better to do this in middleware because it separates the details of how the information is transmitted from the information itself. If I go look at game_scoreboard_json, I don't want to have to read about how it's encoded--- that can be handled elsewhere. Plus, it allows us to take advantage of the existing implementation to do things like not gzip if the client doesn't accept gzip encoding.

2023-05-03 23:02 UTC, n-rook commented on project/thscoreboard/shared_content/static/js/replays/replayTable.js
> +        '<p style="color: red;">Failed to load replays</p>';
Oops! Well, I still don't like it :p but you're right that it's not relevant to this PR.

2023-05-04 15:12 UTC, jgdhs27 commented on project/thscoreboard/replays/views/replay_list.py
> +    replays_json_compressed = gzip.compress(replays_json.encode("utf-8"), 5)
I have no idea how to accomplish that

2023-05-05 01:02 UTC, n-rook commented on project/thscoreboard/replays/views/replay_list.py
> +    replays_json_compressed = gzip.compress(replays_json.encode("utf-8"), 5)
no I mean, I'm pretty sure if you straight up just delete all the gzip code, the gzip middleware that's already installed will just gzip it for you anyway

2023-05-05 18:02 UTC, jgdhs27 commented on project/thscoreboard/replays/views/replay_list.py
> +    replays_json_compressed = gzip.compress(replays_json.encode("utf-8"), 5)
still can't figure it out

2023-05-06 17:31 UTC, n-rook commented on project/thscoreboard/replays/views/replay_list.py
> +    replays_json_compressed = gzip.compress(replays_json.encode("utf-8"), 5)
What are you having trouble with?

Middleware in django (https://docs.djangoproject.com/en/4.2/topics/http/middleware/) basically consists of logic that operates both before and after each view. that's what makes it a good fit for something like compression; we want to compress everything (or at least, we want to compress a lot of things, if they're big enough to be worthwhile), so putting the gzipmiddleware at the top of the middleware list in settings.py allows that to happen automatically for lots of requests, which is better than doing it for only one request. If you do that, even without the code here in replay_list, gzipmiddleware should automatically compress this request for you, and you should be able to see that in something like the Chrome network inspector (because you can look for the gzip tag on the response).

Let me know (or feel free to ping me) if there's anything else you want more information about here from me.

2023-05-06 18:44 UTC, jgdhs27 commented on project/thscoreboard/replays/views/replay_list.py
> +    replays_json_compressed = gzip.compress(replays_json.encode("utf-8"), 5)
For instance if I remove the compression code in python,
```python
    replays_json = json.dumps(converter.convert_replays_to_serializable_list(replays))
    # replays_json_compressed = gzip.compress(replays_json.encode("utf-8"), 5)
    response = HttpResponse(replays_json)
    response["Content-Encoding"] = "gzip"
    return response
```
it doesn't work. I don't know what I'm supposed to do.

2023-05-06 20:19 UTC, n-rook commented on project/thscoreboard/replays/views/replay_list.py
> +    replays_json_compressed = gzip.compress(replays_json.encode("utf-8"), 5)
Oh, I see the issue. You aren't supposed to set Content-Encoding yourself either. If you do, the GZipMiddleware assumes that you already encoded it, so it doesn't do anything; it only works on stuff returned without a Content-Encoding. Instead you should literally just revert replay_list.py and not change it. The main benefit of all this middleware stuff is that you don't have to change the function if you want to add higher-level functionality.

You can actually go look at the source code for Django yourself if you don't understand what it's doing:

https://github.com/django/django/blob/4bf4222010fd8e413963c6c873e4088614332ef9/django/middleware/gzip.py

When I was trying to figure out this middleware, I went into my local installed Django and put stuff like `print('hi im gzip')` in the source so that I could be sure it was actually working.

I uploaded what I did at https://github.com/n-rook/thscoreboard/tree/nrook/gzip-middleware-only if you want to take a look there too.

2023-05-06 20:23 UTC, 32th-System commented on project/thscoreboard/replays/views/replay_list.py
> +    replays_json_compressed = gzip.compress(replays_json.encode("utf-8"), 5)
Wouldn't that gzip compress everything? What if we don't want every page to be gzip compressed?

2023-05-06 20:27 UTC, n-rook commented on project/thscoreboard/replays/views/replay_list.py
> +    replays_json_compressed = gzip.compress(replays_json.encode("utf-8"), 5)
Well, why wouldn't you?

In theory even if we didn't want to gzip everything, I would want to do that by writing our own version of GZipMiddleware and deciding whether or not to gzip stuff based on the responses. I definitely want all _big_ things to be gzipped by default. (or we could install middleware to do brotli or something instead)

2023-05-08 17:37 UTC, jgdhs27 commented
Added nrook's in which everything gzip-related is handled using middleware

2023-05-08 22:33 UTC, n-rook approved these changes
Well, of course I approve :p

2023-05-09 05:33 UTC, merged