Stream replays from DB to frontend
n-rook/thscoreboard pull request #390
Opened 2023-05-09 16:46 UTC by jgdhs27

Stream the replays from the database query all the way to displaying it in the user's browser. This should improve performance, especially when a lot of replays are requested.

It's hard to measure the impact of this change, because performance is fine locally. I tried testing the code using every replay in my DB (50,000 total), but the numbers don't mean much:
Before: Replays appear after 1747ms
After: Replays appear after 923ms
I would like to push this to staging with javascript logging so that we can better understand what it does and see its impact.

2023-05-13 17:17 UTC, n-rook requested changes
Sorry for the review delay, busy week.

I don't really have strong feelings about whether to do this, but if you want, you can keep the old function too, and use an environment variable to call staging based on whether we are in staging or not. that is, just add something to settings.py called IS_STAGING or something, set it to os.environ.get('IS_STAGING', False), and call a different method depending on the situation. this would make the js more complicated though, and plus you'd have to figure out a way to actually get the env variable to the js.

2023-05-13 17:17 UTC, n-rook commented on project/thscoreboard/replays/test_replays_to_json.py
> +                converter._convert_replay_to_dict(replay) for replay in replays
In general, it's best to avoid testing private methods; could you test this instead by calling convert_replays_to_json_strings?

2023-05-13 17:17 UTC, n-rook commented on project/thscoreboard/replays/replays_to_json.py
> +def stream_json_strings_to_http_reponse(
Could you move this function to the view? I think it's cleanest if a module like this one doesn't actually handle HTTP concepts directly, but rather just returns data objects.

2023-05-13 17:24 UTC, 32th-System commented on project/thscoreboard/replays/test_replays_to_json.py
> +                converter._convert_replay_to_dict(replay) for replay in replays
You could also make the method public

2023-05-14 18:56 UTC, jgdhs27 commented
> Sorry for the review delay, busy week.
> 
> I don't really have strong feelings about whether to do this, but if you want, you can keep the old function too, and use an environment variable to call staging based on whether we are in staging or not. that is, just add something to settings.py called IS_STAGING or something, set it to os.environ.get('IS_STAGING', False), and call a different method depending on the situation. this would make the js more complicated though, and plus you'd have to figure out a way to actually get the env variable to the js.

imo, it feels like it would be quite a bit of work, I really think its easier to be a little careful with what we push. It's not like it would be a disaster if this is pushed to production, there are only a few unnwanted console.log's.

2023-05-14 18:58 UTC, jgdhs27 commented on project/thscoreboard/replays/replays_to_json.py
> +    def convert_replay_to_json_string(self, replay: models.Replay) -> str:
good spot

2023-05-14 22:25 UTC, n-rook commented on project/thscoreboard/replays/replays_to_json.py
> +def stream_json_strings_to_http_reponse(
Oh, you're right. I actually kinda feel like maybe this should be one endpoint eventually, and we should customize its behavior from the frontend side. Not in this CL though.

2023-05-14 22:25 UTC, n-rook approved these changes

2023-05-15 06:18 UTC, merged