Allow users to list/unlist replays
n-rook/thscoreboard pull request #392
Opened 2023-05-14 20:10 UTC by jgdhs27

Adds a new flag for each replay, which can be set by the user, to list or unlist replays. unlisted replays are hidden on the main page and the game leaderboards, but still shown on the user profile.

The motivation is that we will soon allow users to claim replays that were imported from royalflare. They might want to hide those replays if they have beaten their pbs. Then unlisting is nicer than deleting, since they can still access their replays, and they are still kept in our database.

2023-05-14 20:33 UTC, 32th-System commented
we already got a "Category" field but the problem with it is that it makes "Tool-Assisted" and "Unlisted" mutually exclusive. Should we get rid of it?

2023-05-14 20:39 UTC, jgdhs27 commented
> we already got a "Category" field but the problem with it is that it makes "Tool-Assisted" and "Unlisted" mutually exclusive. Should we get rid of it?

I think the distinction is still good to have. I want to add a wr history page that includes unlisted but not TAS/Unusual replays.

2023-05-14 22:39 UTC, n-rook requested changes
From a product perspective, I do think this is a good idea. As morth noted, the category field represents what a replay _is_: it's an inherent property of the replay. It would be wrong for someone to upload a replay under the wrong category. But the field this PR adds doesn't really have a "right" value; it's just based on how the player feels.

2023-05-14 22:39 UTC, n-rook commented on project/thscoreboard/replays/constant_helpers.py
> +def GetReplayFileWithSameHash(file) -> Optional[models.ReplayFile]:
This is two logical PRs! The first PR implements a feature to allow users to hide replays from the scoreboard if they don't want them displayed. The second improves the error shown if a duplicate replay is open. Both are good ideas, but I am going to insist you split them into separate PRs.

2023-05-14 22:39 UTC, n-rook commented on project/thscoreboard/replays/templates/replays/replay_details.html
> +            <a href="/replays/{{ game_id }}/{{ replay.id }}/unlist">Hide replay on the leaderboards</a>
We used a separate page for Delete because we didn't want people doing it by accident, but I'm not really convinced a separate page is necessary here. It's not a big deal if someone accidentally unlists a replay, because they can just hit the button again. As such, I think we are better off directly using a button here that immediately does it.

2023-05-15 15:52 UTC, jgdhs27 commented on project/thscoreboard/replays/constant_helpers.py
> +def GetReplayFileWithSameHash(file) -> Optional[models.ReplayFile]:
Ok, this change now exists on #398

2023-05-18 10:32 UTC, jgdhs27 commented on project/thscoreboard/replays/templates/replays/replay_details.html
> +            <a href="/replays/{{ game_id }}/{{ replay.id }}/unlist">Hide replay on the leaderboards</a>
Done. Now it will simply reload the page.

2023-05-20 17:01 UTC, n-rook approved these changes

2023-05-20 17:01 UTC, n-rook commented on project/thscoreboard/replays/views/view_replay.py
> +    return replay_details(request, game_id, replay_id)
If I were doing this I would probably 304 over to replay_details instead, but thinking about it, I don't think there's anything wrong with this way either.

2023-05-20 17:27 UTC, jgdhs27 commented on project/thscoreboard/replays/views/view_replay.py
> +    return replay_details(request, game_id, replay_id)
Didn't know about that! but I tried it out and it didnt seem to update

2023-05-20 17:30 UTC, merged