th128 support
n-rook/thscoreboard pull request #405
Opened 2023-05-20 13:22 UTC by 32th-System

2023-05-20 14:51 UTC, jgdhs27 commented
general comment: please put things in numerical order whenever possible. it makes it a lot easier to find code

2023-05-20 15:05 UTC, jgdhs27 commented
i tried it out and everything seems to work 👍

2023-05-20 17:17 UTC, n-rook requested changes
Thanks for doing this! Scene games are kinda different and will require more work, but 12.8 really was a big hole in the stuff we supported, and it'll be good to have it. Only blocker is that (as morth mentioned), we should really put 12.8 between 12 and 13 in every file where we wind up listing every game in order.

2023-05-20 21:55 UTC, jgdhs27 approved these changes
Cool, just fix the short name used in the frontend

2023-05-20 21:55 UTC, jgdhs27 commented on project/thscoreboard/replays/game_ids.py
> +            pgettext("short game name", "th128"),
It should rather say "th12.8" on the front-end, not "th128"

2023-05-21 08:44 UTC, 32th-System commented on project/thscoreboard/replays/game_ids.py
> +            pgettext("short game name", "th128"),
people ususally don't use the dot for game IDs for point releases

2023-05-21 08:54 UTC, jgdhs27 commented on project/thscoreboard/replays/game_ids.py
> +            pgettext("short game name", "th128"),
I'm not sure where youre getting that info from, and Id be very surprised. royalflare uses 12.8, searching th128 on trs discord gets you to a sarcastic LeSanae poster...

2023-05-21 09:01 UTC, 32th-System commented on project/thscoreboard/replays/game_ids.py
> +            pgettext("short game name", "th128"),
For example, on something like thpatch.net, or in thcrap they don't put the dot. The URL on Royalflare also doesn't have the dot

2023-05-21 09:07 UTC, jgdhs27 commented on project/thscoreboard/replays/game_ids.py
> +            pgettext("short game name", "th128"),
dont mean the url, i mean the game name that's displayed on the front page of ss when you upload a replay

2023-05-21 09:07 UTC, jgdhs27 commented on project/thscoreboard/replays/game_ids.py
> +            pgettext("short game name", "th128"),
thpatch.net uses the dot in this context

2023-05-21 09:09 UTC, jgdhs27 commented on project/thscoreboard/replays/game_ids.py
> +            pgettext("short game name", "th128"),
![image](https://github.com/n-rook/thscoreboard/assets/44336657/b0c5a137-95e7-4efa-ae51-da2258c707cb)
just to be really clear, i am talking about here

2023-05-21 16:29 UTC, n-rook approved these changes

2023-05-21 16:29 UTC, n-rook commented on project/thscoreboard/replays/game_ids.py
> +            pgettext("short game name", "th128"),
This is only showing up because you don't have TL set up locally--- on the production site, strings like "th17" shouldn't ever appear, and it says (for example) WBaWC instead. (Or something else for the JPN site.) So I think it's OK to say th128.

2023-05-21 16:30 UTC, merged