th128: add frozen area
n-rook/thscoreboard pull request #411
Opened 2023-05-25 16:05 UTC by 32th-System

2023-05-25 16:11 UTC, jgdhs27 commented on project/thscoreboard/replays/game_fields.py
> +        "th128_frozen_area": False,
repeated

2023-05-25 16:11 UTC, jgdhs27 commented on project/thscoreboard/replays/game_fields.py
> +            stage.th128_frozen_area = f"{int(stage.th128_frozen_area)}%"
Why are the casts here and in test_replay_parsing.py necessary? According to the `ReplayStage` dataclass, this is already an int

2023-05-28 21:41 UTC, jgdhs27 commented on project/thscoreboard/replays/game_fields.py
> +            stage.th128_frozen_area = f"{int(stage.th128_frozen_area)}%"
This is still an IntegerField according to models.py so something is still off.

2023-05-28 21:44 UTC, jgdhs27 requested changes

2023-05-28 21:44 UTC, jgdhs27 commented on project/thscoreboard/replays/game_fields.py
> +            stage.th128_frozen_area = f"{int(stage.th128_frozen_area)}%"
also, if this is a conversion from float to percentage it looks very strange.uUsually such conversions have a "/100" somewhere. if zun really did use a float value of 100 to represent 100%, consider adding a comment to explain it, because it's really surprising.

2023-05-28 21:46 UTC, jgdhs27 commented on project/thscoreboard/replays/game_fields.py
> +            stage.th128_frozen_area = f"{int(stage.th128_frozen_area)}%"
actually, isnt it usually 100? and the above values use a different convention where 10,000.0 represents 100%? i might be missing something but this looks very strange

2023-05-29 07:03 UTC, 32th-System commented on project/thscoreboard/replays/game_fields.py
> +            stage.th128_frozen_area = f"{int(stage.th128_frozen_area)}%"
Yeah the above percentage is a fixed point integer, while this is a floating point number where 100% is 100. (And where anything after the decimal point gets cut off)

2023-05-29 20:16 UTC, jgdhs27 approved these changes
looks good to me

2023-05-29 20:22 UTC, merged