Create player rankings page
n-rook/thscoreboard pull request #415
Opened 2023-06-01 20:43 UTC by jgdhs27

Create a new player rankings page that shows player's ranks (1st place, 2nd place & third place count) across selected games. A user may pick a specific game, all windows/pc-98 games, or all games.

![image](https://github.com/n-rook/thscoreboard/assets/44336657/fbaff3d8-9ce3-4baa-b088-25dc1105e613)

2023-06-01 23:48 UTC, n-rook requested changes
This is very cool

2023-06-01 23:48 UTC, n-rook commented on project/thscoreboard/replays/get_all_games.py
> +PC98_GAME_IDS = [
I won't insist on it in this PR, because it'd require some restructuring of existing code and be quite the project, but it would really be best if this metadata were actually in the database, rather than having us hardcode it like this.

2023-06-01 23:48 UTC, n-rook commented on project/thscoreboard/replays/views/replay_list.py
> +def get_all_replay_for_game(game_id: str) -> Manager[models.Replay]:
As a general rule, views should not import code from other views. Rather, if we have queries like this which are useful in multiple places, we should put them in a single location (maybe in models.py, maybe in a separate location). After all, nobody would go looking in the views directory to find useful functions that might save them time.

2023-06-01 23:48 UTC, n-rook commented on project/thscoreboard/users/views/rankings.py
> +    if request.method == "POST":
I don't think we should use POST here. It's nice to use GET rather than POST for queries that don't change the database, like this one: most browsers will prompt before refreshing a POST, which is inconvenient for users. Plus, since the POST data isn't present in the URL, a link to it can't be shared. I've never actually written a GET form with Django, but it looks like it supports them cleanly (https://docs.djangoproject.com/en/4.2/topics/forms/#get-and-post) so I think this will not be that hard to change.

2023-06-01 23:48 UTC, n-rook commented on project/thscoreboard/users/views/rankings.py
> +    if len(all_routes) == 0:
Can't you just do `if not all_routes` here, and similar for the other checks? That feels more idiomatic in Python.

2023-06-01 23:48 UTC, n-rook commented on project/thscoreboard/replays/forms.py
> +class RankingGameSelectionForm(forms.Form):
I think this class is a good place to encapsulate the question of "which games should we display". Define a method (something like GetSelectedGameIDs) that will return the selected games, and handle that logic there. Currently, all of this is handled in the view, and you wind up with some circuitous logic there.

2023-06-01 23:48 UTC, n-rook commented on project/thscoreboard/replays/forms.py
> +    DEFAULT_SELECTION = SELECT_WINDOWS
Someday I will complain about this... but for now there are not enough uploads for pc98 games so the data there probably looks dumb. So I'll allow it for now :p

2023-06-01 23:48 UTC, n-rook commented on project/thscoreboard/users/views/rankings.py
> +        all_replays = get_all_replay_for_game(game)
This is going to be a pain in the ass request, and I'm sorry for making it, but I think it's worth doing: Please verify, by inspecting the SQL query used by Django (with something like https://stackoverflow.com/questions/4375784/how-to-log-all-sql-queries-in-django), that we do not fetch every replay in this function. If we fetch every replay, this function will be kinda slow, but we really shouldn't need to for this problem.

2023-06-02 00:10 UTC, n-rook commented on project/thscoreboard/users/views/rankings.py
> +        all_replays = get_all_replay_for_game(game)
Actually, wait, rather than this, you should really just figure out how to get this data directly from the database without having to do all of this computation in Python. Like, this is the sort of problem that databases are good at solving. If you figure out how to query this properly, it should be very fast. However, you will probably have to either use complicated ORM options or just give up and use raw SQL (https://docs.djangoproject.com/en/4.2/topics/db/sql/#performing-raw-queries).

2023-06-02 18:00 UTC, jgdhs27 commented on project/thscoreboard/replays/get_all_games.py
> +PC98_GAME_IDS = [
That makes sense. I might tackle that later, for now i'll make an issue

2023-06-02 18:04 UTC, jgdhs27 commented on project/thscoreboard/replays/views/replay_list.py
> +def get_all_replay_for_game(game_id: str) -> Manager[models.Replay]:
makes sense. in fact this query is probably doing bad performance-wise anyway, so use a new one instead

2023-06-02 18:37 UTC, jgdhs27 commented on project/thscoreboard/users/views/rankings.py
> +        all_replays = get_all_replay_for_game(game)
I'm looking into it and I think Django 4.2's filter-after-window is again perfect for this

2023-06-07 20:26 UTC, jgdhs27 commented on project/thscoreboard/users/views/rankings.py
> +        all_replays = get_all_replay_for_game(game)
Alright, it works like a char,

2023-06-07 20:36 UTC, jgdhs27 commented on project/thscoreboard/replays/forms.py
> +class RankingGameSelectionForm(forms.Form):
done

2023-06-07 20:46 UTC, jgdhs27 commented
It's ready for another review. I have no idea what's causing the CI failure:
`django.db.utils.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "thscoreboard" does not exist`

2023-06-07 20:51 UTC, 32th-System commented
maybe me merging the requirenments.txt update? Try merging main into this branch

2023-06-10 22:33 UTC, jgdhs27 commented
Figured out the issue - I was doing some database queries top-level (TIL class constants are top-level).

But I was playing around one last time and think the calculations for all games are incorrect, so I still need to fix that

2023-06-17 17:50 UTC, n-rook commented
could you close the PR if it's not ready to review right now? not that this is a big deal, but that way I don't have to worry that I'm letting an open PR languish when I should be reviewing it

2023-06-17 18:01 UTC, jgdhs27 commented
ok

2023-07-28 21:16 UTC, jgdhs27 commented
Re-opening this PR. I looked into the ranking weirdness and think I solved it in #435.

2023-07-29 17:44 UTC, n-rook approved these changes
Looks good! Just one comment

2023-07-29 17:44 UTC, n-rook commented on project/thscoreboard/shared_content/static/themes.sass
> -    --table-row-even-color: #ffe6ff
It looks like this was deleted by accident, no?

2023-07-29 18:42 UTC, jgdhs27 commented on project/thscoreboard/shared_content/static/themes.sass
> -    --table-row-even-color: #ffe6ff
Oops! Re-adding it

2023-07-29 18:49 UTC, merged