Seamlessly delete replays that duplicate a new replay but are owned by an inactive user.
n-rook/thscoreboard pull request #468
Opened 2023-09-24 18:16 UTC by n-rook

Fixes #462

2023-09-24 19:49 UTC, jgdhs27 requested changes
works nicely, just some small comments

2023-09-24 19:49 UTC, jgdhs27 commented on project/thscoreboard/replays/create_replay.py
> +    r.save()
im not sure this should be outside the transaction. if there's a non-ghost duplicate, doesnt this mean that the replay saves without the replayfile?

maybe there's an assumption that this function always called within a transaction, but that feels dangerous.

2023-09-24 19:49 UTC, jgdhs27 commented on project/thscoreboard/replays/create_replay.py
> +            or not db_errors.GetUniqueConstraintCause(e) == "unique_hash"
i feel like `"unique_hash"` should be extracted to a constant

2023-09-24 19:49 UTC, jgdhs27 commented on project/thscoreboard/shared_content/test_db_errors.py
> +        try:
this looks like a job for [TestCase.assertRaises()](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises).

2023-09-24 19:49 UTC, jgdhs27 commented on project/thscoreboard/shared_content/test_db_errors.py
> +        try:
same as above

2023-10-02 01:33 UTC, n-rook commented on project/thscoreboard/shared_content/test_db_errors.py
> +        try:
I actually did this on purpose… for reasons that, a week later in hindsight, seem really silly. Done.

2023-10-02 01:36 UTC, n-rook commented on project/thscoreboard/replays/create_replay.py
> +            or not db_errors.GetUniqueConstraintCause(e) == "unique_hash"
This is fair. I just added a classmethod for this. I didn't want to make a top-level constant called REPLAY_FILE_UNIQUE_HASH_CONSTRAINT or whatever. What I actually wanted to do was to either make a class-level constant or reference the constraint object directly, but I couldn't get either to work in a way I liked— the class-level constant couldn't be referenced in the declaration of the constraint, and similarly there wasn't a good way to get the constraint object from another file. So I just gave up and did this.

2023-10-02 01:39 UTC, n-rook commented on project/thscoreboard/replays/create_replay.py
> +    r.save()
Eh… Since it's a private function I think it's fine. Were it a public function I would agree that either it should be a transaction or there should be a really big warning in the docstring not to call it outside of a transaction, and probably the former. But an extra transaction does have some overhead (even if it's pretty slight) so I think it's better to avoid it when possible.

2023-10-02 01:43 UTC, n-rook commented on project/thscoreboard/replays/create_replay.py
> +    r.save()
Looking at this function now I'm not sure why r.save() is even in here, so I moved it out. (But this conversation is still relevant, since the function still isn't safe outside of a transaction.)

2023-10-02 06:36 UTC, jgdhs27 commented on project/thscoreboard/replays/create_replay.py
> +    r.save()
I like this approach

2023-10-02 06:36 UTC, jgdhs27 approved these changes

2023-10-06 16:39 UTC, merged