[DO NOT MERGE] Add a page allowing users to edit a replay
n-rook/thscoreboard pull request #484
Opened 2023-10-13 20:37 UTC by n-rook

The edit replay page can be used to edit the metadata of an existing replay. I reuse the "finalize publishing replay" page for this purpose. You can't change the actual file, but you can change everything else.

PC-98 games aren't supported, not for any particular reason but because this PR is big enough as it is.

DO NOT MERGE: This PR's merge target is set to #482 to make the diff look right, but obviously we do not actually want to merge it to #482; we want to merge it once #482 is in.

#453, #455

2023-10-15 16:17 UTC, n-rook commented
Now that #482 is in, this is ready to merge.

2023-10-29 08:51 UTC, jgdhs27 requested changes
cool, i love this feature. just some small things

2023-10-29 08:51 UTC, jgdhs27 commented on project/thscoreboard/replays/views/test_edit_replay.py
> +        self.assertEqual(response.status_code, 403)
this test is identical to the previous one

2023-12-22 18:09 UTC, n-rook commented on project/thscoreboard/replays/views/edit_replay.py
> +    else:
This is actually correct. We only need to initialize the form if the user did not send us any data; even if their data is invalid we can still use the form object read from their POST (and indeed, we should, so that we don't lose their changes and so that their errors appear properly). I added a test for this

2023-12-22 18:09 UTC, n-rook commented on project/thscoreboard/replays/urls/replay_urls.py
> +    path("<str:game_id>/<int:replay_id>/edit_comment", view_replay.edit_replay),
Good catch, done

2023-12-22 18:09 UTC, n-rook commented on project/thscoreboard/replays/views/test_edit_replay.py
> +        self.assertEqual(response.status_code, 403)
Oops… Fixed

2023-12-27 15:56 UTC, jgdhs27 approved these changes
nice!

2023-12-27 18:28 UTC, merged

2023-12-27 18:29 UTC, n-rook commented
Thanks for the review!