th06 stage splits
n-rook/thscoreboard pull request #54
Opened 2022-09-18 07:44 UTC by raviddog

2022-09-18 17:59 UTC, n-rook requested changes
Thanks, it'll be great to have this in!

2022-09-18 17:59 UTC, n-rook commented on project/thscoreboard/replays/kaitai_parsers/th06.py
> +                self._io.seek(self.header.stage_offsets[i]-15)
I don't think we should have to implement the -15 ourselves. In theory these source files should require no customization after being generated from the Kaitai Struct files, right? So I think it would be better to apply this -15 there. I don't know KS well and don't have a compilation chain set up yet, but I think something as simple as `pos: header.stage_offsets[_index] - 15` would work, right?

2022-09-18 17:59 UTC, n-rook commented on project/thscoreboard/replays/kaitai_parsers/th06.py
> -        self._io.seek(self.header.stage_offsets[i])
We should file an issue about the fact that we need to do these manual interventions in the Kaitai Struct generated code. It would be best if we didn't have to modify these source files at all. Could you file a bug for this?

The issue on our side would have two possible resolutions:
- Work around this issue, or if it's caused by a bug in our struct definitions, fix the bug. (It doesn't seem like there's anything wrong with our definitions, so this seems kind of unlikely)
- Figure out a minimal reproduction of the bug, file a bug against Kaitai Struct, and maybe even send them a pull request to fix the bug

But really, fixing it would not be a high priority or anything. I just want a bug so we don't forget this is a thing.

2022-09-18 17:59 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +class ReplayStage(models.Model):
I think for the model, we should document exactly which games the fields belong to, at least for the shared fields (that is... it goes without saying that `th06_rank` is only set for th06). We should also note if the field is always set for a game or not.

For example we might say:

graze = ...
"""The number of grazes the player has made at the beginning of the stage.

Set for:
- th06 (required)
- ...
```

Of course, for now you would just say "th06" for everything and not cover other games, since it is the only one implemented. But it will make it easier to keep track of later.

2022-09-18 17:59 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +    """Represents a stage split for a given replay"""
Do the fields in this model refer to the state at the beginning of the stage, or at the end? I think I know the answer but we should still note it down somewhere.

2022-09-18 17:59 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +class ReplayStage(models.Model):
We should document every field. I know even I haven't been completely diligent about this, but I do think it's the way to go. The database is always the most important part of the codebase for people to know exactly what each field or row means. After all, if there is a bug in code it is usually easy to just fix and deploy it, but if bad data gets into the database it can be much more annoying to track down and fix.

IMO the "hierarchy of docs" is as follows:
1. Anything used as an interface between the server and something outside the server. This includes APIs and the database. These are the most important to document, because they tend to be used in many places. Plus, it is difficult to tell what the definitions are just by looking at code; you generally have to look in lots of different places to figure it out. (In theory HTML views would be included here... but in reality it is basically impossible to document those well since they're big documents, they're not something like a JSON response that is easy to describe.)
2. Any public function, method, etc. in a module. These are still important to document, because it's good for coders to be able to use them without having to actually read their implementation. But it's less important than (1) because you generally only need to read the function definition and maybe its tests to figure out mostly how it works.
3. Anything that isn't public in a module. I generally don't bother documenting these (or use a one-line docstring) unless they are unusually complicated.

2022-09-18 17:59 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +    score = models.BigIntegerField(blank=True, null=True)
`score` shouldn't be nullable, right?

2022-09-18 17:59 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +    """The stage this split corresponds to in the replay"""
Does this start at 0 or 1? What is the stage number for extra? (I think I know the answer to these, but for database stuff it's best to be really explicit.)

2022-09-18 17:59 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +    r.stages = rep_stages
Nitpick: I think it's slightly better style to pass it into the ReplayInfo constructor directly.

2022-09-18 17:59 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +    for score in replay.stages:
We should add tests for all these changes. They should be pretty easy to write.

2022-09-19 02:49 UTC, raviddog commented on project/thscoreboard/replays/replay_parsing.py
> +    for score in replay.stages:
i already have a separate branch set up that i plan to create a PR once this gets merged

2022-09-19 02:49 UTC, raviddog commented on project/thscoreboard/replays/kaitai_parsers/th06.py
> +                self._io.seek(self.header.stage_offsets[i]-15)
i agree, maybe create an issue so we don't forget, but i just wanted this stupid thing working so i could actually make progress

2022-09-19 02:50 UTC, raviddog commented on project/thscoreboard/replays/kaitai_parsers/th06.py
> -        self._io.seek(self.header.stage_offsets[i])
see comment about -15

2022-09-19 02:52 UTC, raviddog commented on project/thscoreboard/replays/models.py
> +class ReplayStage(models.Model):
theres so much variation here that im kinda scared to do it as code comments because itll bloat the file and make the lines really far from each other. i want to be able to see all the fields in this table at a quick glance, so yeah idk.

2022-09-19 02:53 UTC, raviddog commented on project/thscoreboard/replays/models.py
> +    """Represents a stage split for a given replay"""
the beginning, except for th07 which stores the end because zun is inconsistent. we could "fix" this because we know what values you start with but idk, raise an issue so we can discuess fuether i guess

2022-09-19 02:55 UTC, raviddog commented on project/thscoreboard/replays/models.py
> +    score = models.BigIntegerField(blank=True, null=True)
i dont trust zun
but yeah youre right, and we can always change this

2022-09-19 02:56 UTC, raviddog commented on project/thscoreboard/replays/replay_parsing.py
> +    r.stages = rep_stages
i would have to manually declare the __init__ constructor because python doesnt include an empty array in the default one and i dont know how that works and there were like 16 errors i had to fight through to get this PR working

2022-09-19 02:58 UTC, raviddog commented on project/thscoreboard/replays/models.py
> +    """The stage this split corresponds to in the replay"""
0-5 is regular, extra is 6, except in IN where it gets bloated by the A and B stages so as usual zun is inconsistent and the correct stage text should just be handled by the frontend IMO

2022-09-19 03:53 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +    r.stages = rep_stages
Can't you just do

```
    r = ReplayInfo(
        game_ids.GameIDs.TH06,
        shots[rep_raw[6]],
        rep_raw[7],
        replay.header.score,
        datetime.strptime(replay.header.date, "%m/%d/%y"),
        stages=rep_stages
    )
```

? That's all I mean.

2022-09-19 03:53 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +    for score in replay.stages:
I'm worried there are bugs I'm not seeing in this code, so I'm not comfortable merging this PR until there are basic tests included. In software development, it's almost always best to add code and unit tests at the same time. git has tools to get files from other branches so it should not be too bad to put the tests in here.

2022-09-19 03:53 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +class ReplayStage(models.Model):
You've got to remember that not everyone working on the frontend will know what these fields correspond to in the replay file. Even if you know at a glance, nobody else will know. Even though it's annoying to have wordy comments, it's better than having me guessing at what these fields mean and adding bugs to the frontend because I don't understand them.

I do actually want to split this file up like I did `views/` because it is already too big, but I know it will cause merge conflicts for everyone when I do so I have been putting it off

2022-09-19 03:53 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +    """Represents a stage split for a given replay"""
Good thing I asked, that wasn't what I would have guessed! I actually think it's a big problem if these rows represent the start for some games and the end for others. It'll be really hard to design a consistent UI if that's the case. For now could you save only stages for eosd and mof in this PR, and then send another PR later for pcb? That way we can deal with it later without holding up this.

2022-09-19 03:53 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +    score = models.BigIntegerField(blank=True, null=True)
yeah that's the other thing, it's easy to remove restrictions later, but harder to add them (not impossible or anything, but harder)

2022-09-19 03:53 UTC, n-rook commented on project/thscoreboard/replays/kaitai_parsers/th06.py
> +                self._io.seek(self.header.stage_offsets[i]-15)
yeah I can see why you were so frustrated by the Kaitai Struct bug!

2022-09-19 03:53 UTC, n-rook commented on project/thscoreboard/replays/models.py
> +    """The stage this split corresponds to in the replay"""
we should think about just doing this ourselves and always making them ordered from 0, but I don't think it matters enough to do it in this pr

2022-09-19 04:21 UTC, raviddog commented on project/thscoreboard/replays/replay_parsing.py
> +    r.stages = rep_stages
i tried that and it refused and i had enough broken things on my plate at the time

2022-09-19 14:36 UTC, raviddog commented on project/thscoreboard/replays/kaitai_parsers/th06.py
> -        self._io.seek(self.header.stage_offsets[i])
#61

2022-09-19 14:37 UTC, raviddog commented on project/thscoreboard/replays/models.py
> +class ReplayStage(models.Model):
addressed

2022-09-19 14:38 UTC, raviddog commented on project/thscoreboard/replays/models.py
> +class ReplayStage(models.Model):
#62

2022-09-19 14:40 UTC, raviddog commented on project/thscoreboard/replays/replay_parsing.py
> +    for score in replay.stages:
addressed.
more tests can be added in the future, specifically I'd like to add some that involve storing and retrieving from the database.
But these changes should suffice for the current splits feature being added

2022-09-19 14:41 UTC, raviddog commented on project/thscoreboard/replays/kaitai_parsers/th06.py
> +                self._io.seek(self.header.stage_offsets[i]-15)
I've edited the .ksy file to include this, I tested and this is indeed the same code it produces with the -15 added.

2022-09-19 14:42 UTC, raviddog commented on project/thscoreboard/replays/models.py
> +    """Represents a stage split for a given replay"""
I've added this info as a comment

2022-09-19 14:42 UTC, raviddog commented on project/thscoreboard/replays/models.py
> +    score = models.BigIntegerField(blank=True, null=True)
addressed

2022-09-19 21:39 UTC, n-rook approved these changes

2022-09-19 21:39 UTC, n-rook commented on project/thscoreboard/replays/replay_parsing.py
> +    for score in replay.stages:
yeah, it's great to have lots of tests, but all I think we really _need_ for this PR is basic tests that show the feature works at all

2022-09-19 21:39 UTC, merged