Th11 support
n-rook/thscoreboard pull request #89
Opened 2022-11-05 04:13 UTC by raviddog

2022-11-05 15:40 UTC, n-rook requested changes
Test, please!

2022-11-05 15:40 UTC, n-rook commented on project/thscoreboard/replays/game_fields.py
> +        return "%.2f" % (float(power) * 0.05)
Rather than repeating this line, I think it'd be better to group the conditionals like so:

```
if game_id in {game_ids.GameIDs.TH06, game_ids.GameIDs.TH07}:
  return str(power)
elif game_id in {game_ids.GameIDs.TH10, ...}:
  return ...
```

2022-11-07 07:33 UTC, raviddog commented on project/thscoreboard/replays/game_fields.py
> +        return "%.2f" % (float(power) * 0.05)
I left them separate to make it easier to see which games have been added, but I guess yeah you can just ctrl F it

2022-11-07 15:27 UTC, n-rook approved these changes
pog

I'm not sure if you're actually done yet, so I'm not merging it myself, but if you are done you can merge it

2022-11-07 15:27 UTC, n-rook commented on project/thscoreboard/replays/forms.py
> +    ('th11', '東方地霊殿 - Subterranean Animism')
Optional: There's a Python trick you can use here. You can put an extra comma at the end of a tuple like this, so that the diffs look better in the future, and you don't have to remember to add another one when you add more games.

2022-11-07 18:31 UTC, merged